/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the MdmServiceProfilesDeviceEnrollmentProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MdmServiceProfilesDeviceEnrollmentProfile{}

// MdmServiceProfilesDeviceEnrollmentProfile struct for MdmServiceProfilesDeviceEnrollmentProfile
type MdmServiceProfilesDeviceEnrollmentProfile struct {
	HasRemovalPasscode       *bool                                `json:"has_removal_passcode,omitempty"`
	InstalledPayloads        []MdmServiceProfilesInstalledPayload `json:"installed_payloads,omitempty"`
	IsEncrypted              *bool                                `json:"is_encrypted,omitempty"`
	LastUpdated              *string                              `json:"last_updated,omitempty"`
	PayloadDescription       *string                              `json:"payload_description,omitempty"`
	PayloadDisplayName       *string                              `json:"payload_display_name,omitempty"`
	PayloadIdentifier        *string                              `json:"payload_identifier,omitempty"`
	PayloadOrganization      *string                              `json:"payload_organization,omitempty"`
	PayloadRemovalDisallowed *bool                                `json:"payload_removal_disallowed,omitempty"`
	PayloadUuid              *string                              `json:"payload_uuid,omitempty"`
	PayloadVersion           map[string]interface{}               `json:"payload_version,omitempty"`
	Priority                 *float32                             `json:"priority,omitempty"`
	Udid                     *string                              `json:"udid,omitempty"`
	UserId                   *string                              `json:"user_id,omitempty"`
	AdditionalProperties     map[string]interface{}
}

type _MdmServiceProfilesDeviceEnrollmentProfile MdmServiceProfilesDeviceEnrollmentProfile

// NewMdmServiceProfilesDeviceEnrollmentProfile instantiates a new MdmServiceProfilesDeviceEnrollmentProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMdmServiceProfilesDeviceEnrollmentProfile() *MdmServiceProfilesDeviceEnrollmentProfile {
	this := MdmServiceProfilesDeviceEnrollmentProfile{}
	return &this
}

// NewMdmServiceProfilesDeviceEnrollmentProfileWithDefaults instantiates a new MdmServiceProfilesDeviceEnrollmentProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMdmServiceProfilesDeviceEnrollmentProfileWithDefaults() *MdmServiceProfilesDeviceEnrollmentProfile {
	this := MdmServiceProfilesDeviceEnrollmentProfile{}
	return &this
}

// GetHasRemovalPasscode returns the HasRemovalPasscode field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetHasRemovalPasscode() bool {
	if o == nil || IsNil(o.HasRemovalPasscode) {
		var ret bool
		return ret
	}
	return *o.HasRemovalPasscode
}

// GetHasRemovalPasscodeOk returns a tuple with the HasRemovalPasscode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetHasRemovalPasscodeOk() (*bool, bool) {
	if o == nil || IsNil(o.HasRemovalPasscode) {
		return nil, false
	}
	return o.HasRemovalPasscode, true
}

// HasHasRemovalPasscode returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasHasRemovalPasscode() bool {
	if o != nil && !IsNil(o.HasRemovalPasscode) {
		return true
	}

	return false
}

// SetHasRemovalPasscode gets a reference to the given bool and assigns it to the HasRemovalPasscode field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetHasRemovalPasscode(v bool) {
	o.HasRemovalPasscode = &v
}

// GetInstalledPayloads returns the InstalledPayloads field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetInstalledPayloads() []MdmServiceProfilesInstalledPayload {
	if o == nil || IsNil(o.InstalledPayloads) {
		var ret []MdmServiceProfilesInstalledPayload
		return ret
	}
	return o.InstalledPayloads
}

// GetInstalledPayloadsOk returns a tuple with the InstalledPayloads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetInstalledPayloadsOk() ([]MdmServiceProfilesInstalledPayload, bool) {
	if o == nil || IsNil(o.InstalledPayloads) {
		return nil, false
	}
	return o.InstalledPayloads, true
}

// HasInstalledPayloads returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasInstalledPayloads() bool {
	if o != nil && !IsNil(o.InstalledPayloads) {
		return true
	}

	return false
}

// SetInstalledPayloads gets a reference to the given []MdmServiceProfilesInstalledPayload and assigns it to the InstalledPayloads field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetInstalledPayloads(v []MdmServiceProfilesInstalledPayload) {
	o.InstalledPayloads = v
}

// GetIsEncrypted returns the IsEncrypted field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetIsEncrypted() bool {
	if o == nil || IsNil(o.IsEncrypted) {
		var ret bool
		return ret
	}
	return *o.IsEncrypted
}

// GetIsEncryptedOk returns a tuple with the IsEncrypted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetIsEncryptedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEncrypted) {
		return nil, false
	}
	return o.IsEncrypted, true
}

// HasIsEncrypted returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasIsEncrypted() bool {
	if o != nil && !IsNil(o.IsEncrypted) {
		return true
	}

	return false
}

// SetIsEncrypted gets a reference to the given bool and assigns it to the IsEncrypted field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetIsEncrypted(v bool) {
	o.IsEncrypted = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetLastUpdated() string {
	if o == nil || IsNil(o.LastUpdated) {
		var ret string
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetLastUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given string and assigns it to the LastUpdated field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetLastUpdated(v string) {
	o.LastUpdated = &v
}

// GetPayloadDescription returns the PayloadDescription field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadDescription() string {
	if o == nil || IsNil(o.PayloadDescription) {
		var ret string
		return ret
	}
	return *o.PayloadDescription
}

// GetPayloadDescriptionOk returns a tuple with the PayloadDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.PayloadDescription) {
		return nil, false
	}
	return o.PayloadDescription, true
}

// HasPayloadDescription returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasPayloadDescription() bool {
	if o != nil && !IsNil(o.PayloadDescription) {
		return true
	}

	return false
}

// SetPayloadDescription gets a reference to the given string and assigns it to the PayloadDescription field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetPayloadDescription(v string) {
	o.PayloadDescription = &v
}

// GetPayloadDisplayName returns the PayloadDisplayName field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadDisplayName() string {
	if o == nil || IsNil(o.PayloadDisplayName) {
		var ret string
		return ret
	}
	return *o.PayloadDisplayName
}

// GetPayloadDisplayNameOk returns a tuple with the PayloadDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.PayloadDisplayName) {
		return nil, false
	}
	return o.PayloadDisplayName, true
}

// HasPayloadDisplayName returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasPayloadDisplayName() bool {
	if o != nil && !IsNil(o.PayloadDisplayName) {
		return true
	}

	return false
}

// SetPayloadDisplayName gets a reference to the given string and assigns it to the PayloadDisplayName field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetPayloadDisplayName(v string) {
	o.PayloadDisplayName = &v
}

// GetPayloadIdentifier returns the PayloadIdentifier field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadIdentifier() string {
	if o == nil || IsNil(o.PayloadIdentifier) {
		var ret string
		return ret
	}
	return *o.PayloadIdentifier
}

// GetPayloadIdentifierOk returns a tuple with the PayloadIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.PayloadIdentifier) {
		return nil, false
	}
	return o.PayloadIdentifier, true
}

// HasPayloadIdentifier returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasPayloadIdentifier() bool {
	if o != nil && !IsNil(o.PayloadIdentifier) {
		return true
	}

	return false
}

// SetPayloadIdentifier gets a reference to the given string and assigns it to the PayloadIdentifier field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetPayloadIdentifier(v string) {
	o.PayloadIdentifier = &v
}

// GetPayloadOrganization returns the PayloadOrganization field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadOrganization() string {
	if o == nil || IsNil(o.PayloadOrganization) {
		var ret string
		return ret
	}
	return *o.PayloadOrganization
}

// GetPayloadOrganizationOk returns a tuple with the PayloadOrganization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.PayloadOrganization) {
		return nil, false
	}
	return o.PayloadOrganization, true
}

// HasPayloadOrganization returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasPayloadOrganization() bool {
	if o != nil && !IsNil(o.PayloadOrganization) {
		return true
	}

	return false
}

// SetPayloadOrganization gets a reference to the given string and assigns it to the PayloadOrganization field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetPayloadOrganization(v string) {
	o.PayloadOrganization = &v
}

// GetPayloadRemovalDisallowed returns the PayloadRemovalDisallowed field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadRemovalDisallowed() bool {
	if o == nil || IsNil(o.PayloadRemovalDisallowed) {
		var ret bool
		return ret
	}
	return *o.PayloadRemovalDisallowed
}

// GetPayloadRemovalDisallowedOk returns a tuple with the PayloadRemovalDisallowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadRemovalDisallowedOk() (*bool, bool) {
	if o == nil || IsNil(o.PayloadRemovalDisallowed) {
		return nil, false
	}
	return o.PayloadRemovalDisallowed, true
}

// HasPayloadRemovalDisallowed returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasPayloadRemovalDisallowed() bool {
	if o != nil && !IsNil(o.PayloadRemovalDisallowed) {
		return true
	}

	return false
}

// SetPayloadRemovalDisallowed gets a reference to the given bool and assigns it to the PayloadRemovalDisallowed field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetPayloadRemovalDisallowed(v bool) {
	o.PayloadRemovalDisallowed = &v
}

// GetPayloadUuid returns the PayloadUuid field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadUuid() string {
	if o == nil || IsNil(o.PayloadUuid) {
		var ret string
		return ret
	}
	return *o.PayloadUuid
}

// GetPayloadUuidOk returns a tuple with the PayloadUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadUuidOk() (*string, bool) {
	if o == nil || IsNil(o.PayloadUuid) {
		return nil, false
	}
	return o.PayloadUuid, true
}

// HasPayloadUuid returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasPayloadUuid() bool {
	if o != nil && !IsNil(o.PayloadUuid) {
		return true
	}

	return false
}

// SetPayloadUuid gets a reference to the given string and assigns it to the PayloadUuid field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetPayloadUuid(v string) {
	o.PayloadUuid = &v
}

// GetPayloadVersion returns the PayloadVersion field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadVersion() map[string]interface{} {
	if o == nil || IsNil(o.PayloadVersion) {
		var ret map[string]interface{}
		return ret
	}
	return o.PayloadVersion
}

// GetPayloadVersionOk returns a tuple with the PayloadVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPayloadVersionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PayloadVersion) {
		return map[string]interface{}{}, false
	}
	return o.PayloadVersion, true
}

// HasPayloadVersion returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasPayloadVersion() bool {
	if o != nil && !IsNil(o.PayloadVersion) {
		return true
	}

	return false
}

// SetPayloadVersion gets a reference to the given map[string]interface{} and assigns it to the PayloadVersion field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetPayloadVersion(v map[string]interface{}) {
	o.PayloadVersion = v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPriority() float32 {
	if o == nil || IsNil(o.Priority) {
		var ret float32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetPriorityOk() (*float32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given float32 and assigns it to the Priority field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetPriority(v float32) {
	o.Priority = &v
}

// GetUdid returns the Udid field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetUdid() string {
	if o == nil || IsNil(o.Udid) {
		var ret string
		return ret
	}
	return *o.Udid
}

// GetUdidOk returns a tuple with the Udid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetUdidOk() (*string, bool) {
	if o == nil || IsNil(o.Udid) {
		return nil, false
	}
	return o.Udid, true
}

// HasUdid returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasUdid() bool {
	if o != nil && !IsNil(o.Udid) {
		return true
	}

	return false
}

// SetUdid gets a reference to the given string and assigns it to the Udid field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetUdid(v string) {
	o.Udid = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *MdmServiceProfilesDeviceEnrollmentProfile) SetUserId(v string) {
	o.UserId = &v
}

func (o MdmServiceProfilesDeviceEnrollmentProfile) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MdmServiceProfilesDeviceEnrollmentProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasRemovalPasscode) {
		toSerialize["has_removal_passcode"] = o.HasRemovalPasscode
	}
	if !IsNil(o.InstalledPayloads) {
		toSerialize["installed_payloads"] = o.InstalledPayloads
	}
	if !IsNil(o.IsEncrypted) {
		toSerialize["is_encrypted"] = o.IsEncrypted
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["last_updated"] = o.LastUpdated
	}
	if !IsNil(o.PayloadDescription) {
		toSerialize["payload_description"] = o.PayloadDescription
	}
	if !IsNil(o.PayloadDisplayName) {
		toSerialize["payload_display_name"] = o.PayloadDisplayName
	}
	if !IsNil(o.PayloadIdentifier) {
		toSerialize["payload_identifier"] = o.PayloadIdentifier
	}
	if !IsNil(o.PayloadOrganization) {
		toSerialize["payload_organization"] = o.PayloadOrganization
	}
	if !IsNil(o.PayloadRemovalDisallowed) {
		toSerialize["payload_removal_disallowed"] = o.PayloadRemovalDisallowed
	}
	if !IsNil(o.PayloadUuid) {
		toSerialize["payload_uuid"] = o.PayloadUuid
	}
	if !IsNil(o.PayloadVersion) {
		toSerialize["payload_version"] = o.PayloadVersion
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Udid) {
		toSerialize["udid"] = o.Udid
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MdmServiceProfilesDeviceEnrollmentProfile) UnmarshalJSON(data []byte) (err error) {
	varMdmServiceProfilesDeviceEnrollmentProfile := _MdmServiceProfilesDeviceEnrollmentProfile{}

	err = json.Unmarshal(data, &varMdmServiceProfilesDeviceEnrollmentProfile)

	if err != nil {
		return err
	}

	*o = MdmServiceProfilesDeviceEnrollmentProfile(varMdmServiceProfilesDeviceEnrollmentProfile)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "has_removal_passcode")
		delete(additionalProperties, "installed_payloads")
		delete(additionalProperties, "is_encrypted")
		delete(additionalProperties, "last_updated")
		delete(additionalProperties, "payload_description")
		delete(additionalProperties, "payload_display_name")
		delete(additionalProperties, "payload_identifier")
		delete(additionalProperties, "payload_organization")
		delete(additionalProperties, "payload_removal_disallowed")
		delete(additionalProperties, "payload_uuid")
		delete(additionalProperties, "payload_version")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "udid")
		delete(additionalProperties, "user_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMdmServiceProfilesDeviceEnrollmentProfile struct {
	value *MdmServiceProfilesDeviceEnrollmentProfile
	isSet bool
}

func (v NullableMdmServiceProfilesDeviceEnrollmentProfile) Get() *MdmServiceProfilesDeviceEnrollmentProfile {
	return v.value
}

func (v *NullableMdmServiceProfilesDeviceEnrollmentProfile) Set(val *MdmServiceProfilesDeviceEnrollmentProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableMdmServiceProfilesDeviceEnrollmentProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableMdmServiceProfilesDeviceEnrollmentProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMdmServiceProfilesDeviceEnrollmentProfile(val *MdmServiceProfilesDeviceEnrollmentProfile) *NullableMdmServiceProfilesDeviceEnrollmentProfile {
	return &NullableMdmServiceProfilesDeviceEnrollmentProfile{value: val, isSet: true}
}

func (v NullableMdmServiceProfilesDeviceEnrollmentProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMdmServiceProfilesDeviceEnrollmentProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
