/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the ClientAgentThreatDetectionInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientAgentThreatDetectionInfo{}

// ClientAgentThreatDetectionInfo struct for ClientAgentThreatDetectionInfo
type ClientAgentThreatDetectionInfo struct {
	AccountId                 *string                                      `json:"accountId,omitempty"`
	AccountName               *string                                      `json:"accountName,omitempty"`
	AgentDetectionState       *string                                      `json:"agentDetectionState,omitempty"`
	AgentDomain               *string                                      `json:"agentDomain,omitempty"`
	AgentIpV4                 *string                                      `json:"agentIpV4,omitempty"`
	AgentIpV6                 *string                                      `json:"agentIpV6,omitempty"`
	AgentLastLoggedInUpn      *string                                      `json:"agentLastLoggedInUpn,omitempty"`
	AgentLastLoggedInUserMail *string                                      `json:"agentLastLoggedInUserMail,omitempty"`
	AgentLastLoggedInUserName *string                                      `json:"agentLastLoggedInUserName,omitempty"`
	AgentMitigationMode       *string                                      `json:"agentMitigationMode,omitempty"`
	AgentOsName               *string                                      `json:"agentOsName,omitempty"`
	AgentOsRevision           *string                                      `json:"agentOsRevision,omitempty"`
	AgentRegisteredAt         *string                                      `json:"agentRegisteredAt,omitempty"`
	AgentUuid                 *string                                      `json:"agentUuid,omitempty"`
	AgentVersion              *string                                      `json:"agentVersion,omitempty"`
	AssetVersion              *string                                      `json:"assetVersion,omitempty"`
	CloudProviders            *map[string]ClientDetectionInfoCloudProvider `json:"cloudProviders,omitempty"`
	ExternalIp                *string                                      `json:"externalIp,omitempty"`
	GroupId                   *string                                      `json:"groupId,omitempty"`
	GroupName                 *string                                      `json:"groupName,omitempty"`
	SiteId                    *string                                      `json:"siteId,omitempty"`
	SiteName                  *string                                      `json:"siteName,omitempty"`
	AdditionalProperties      map[string]interface{}
}

type _ClientAgentThreatDetectionInfo ClientAgentThreatDetectionInfo

// NewClientAgentThreatDetectionInfo instantiates a new ClientAgentThreatDetectionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientAgentThreatDetectionInfo() *ClientAgentThreatDetectionInfo {
	this := ClientAgentThreatDetectionInfo{}
	return &this
}

// NewClientAgentThreatDetectionInfoWithDefaults instantiates a new ClientAgentThreatDetectionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientAgentThreatDetectionInfoWithDefaults() *ClientAgentThreatDetectionInfo {
	this := ClientAgentThreatDetectionInfo{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *ClientAgentThreatDetectionInfo) SetAccountId(v string) {
	o.AccountId = &v
}

// GetAccountName returns the AccountName field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAccountName() string {
	if o == nil || IsNil(o.AccountName) {
		var ret string
		return ret
	}
	return *o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAccountNameOk() (*string, bool) {
	if o == nil || IsNil(o.AccountName) {
		return nil, false
	}
	return o.AccountName, true
}

// HasAccountName returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAccountName() bool {
	if o != nil && !IsNil(o.AccountName) {
		return true
	}

	return false
}

// SetAccountName gets a reference to the given string and assigns it to the AccountName field.
func (o *ClientAgentThreatDetectionInfo) SetAccountName(v string) {
	o.AccountName = &v
}

// GetAgentDetectionState returns the AgentDetectionState field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentDetectionState() string {
	if o == nil || IsNil(o.AgentDetectionState) {
		var ret string
		return ret
	}
	return *o.AgentDetectionState
}

// GetAgentDetectionStateOk returns a tuple with the AgentDetectionState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentDetectionStateOk() (*string, bool) {
	if o == nil || IsNil(o.AgentDetectionState) {
		return nil, false
	}
	return o.AgentDetectionState, true
}

// HasAgentDetectionState returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentDetectionState() bool {
	if o != nil && !IsNil(o.AgentDetectionState) {
		return true
	}

	return false
}

// SetAgentDetectionState gets a reference to the given string and assigns it to the AgentDetectionState field.
func (o *ClientAgentThreatDetectionInfo) SetAgentDetectionState(v string) {
	o.AgentDetectionState = &v
}

// GetAgentDomain returns the AgentDomain field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentDomain() string {
	if o == nil || IsNil(o.AgentDomain) {
		var ret string
		return ret
	}
	return *o.AgentDomain
}

// GetAgentDomainOk returns a tuple with the AgentDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentDomainOk() (*string, bool) {
	if o == nil || IsNil(o.AgentDomain) {
		return nil, false
	}
	return o.AgentDomain, true
}

// HasAgentDomain returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentDomain() bool {
	if o != nil && !IsNil(o.AgentDomain) {
		return true
	}

	return false
}

// SetAgentDomain gets a reference to the given string and assigns it to the AgentDomain field.
func (o *ClientAgentThreatDetectionInfo) SetAgentDomain(v string) {
	o.AgentDomain = &v
}

// GetAgentIpV4 returns the AgentIpV4 field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentIpV4() string {
	if o == nil || IsNil(o.AgentIpV4) {
		var ret string
		return ret
	}
	return *o.AgentIpV4
}

// GetAgentIpV4Ok returns a tuple with the AgentIpV4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentIpV4Ok() (*string, bool) {
	if o == nil || IsNil(o.AgentIpV4) {
		return nil, false
	}
	return o.AgentIpV4, true
}

// HasAgentIpV4 returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentIpV4() bool {
	if o != nil && !IsNil(o.AgentIpV4) {
		return true
	}

	return false
}

// SetAgentIpV4 gets a reference to the given string and assigns it to the AgentIpV4 field.
func (o *ClientAgentThreatDetectionInfo) SetAgentIpV4(v string) {
	o.AgentIpV4 = &v
}

// GetAgentIpV6 returns the AgentIpV6 field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentIpV6() string {
	if o == nil || IsNil(o.AgentIpV6) {
		var ret string
		return ret
	}
	return *o.AgentIpV6
}

// GetAgentIpV6Ok returns a tuple with the AgentIpV6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentIpV6Ok() (*string, bool) {
	if o == nil || IsNil(o.AgentIpV6) {
		return nil, false
	}
	return o.AgentIpV6, true
}

// HasAgentIpV6 returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentIpV6() bool {
	if o != nil && !IsNil(o.AgentIpV6) {
		return true
	}

	return false
}

// SetAgentIpV6 gets a reference to the given string and assigns it to the AgentIpV6 field.
func (o *ClientAgentThreatDetectionInfo) SetAgentIpV6(v string) {
	o.AgentIpV6 = &v
}

// GetAgentLastLoggedInUpn returns the AgentLastLoggedInUpn field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentLastLoggedInUpn() string {
	if o == nil || IsNil(o.AgentLastLoggedInUpn) {
		var ret string
		return ret
	}
	return *o.AgentLastLoggedInUpn
}

// GetAgentLastLoggedInUpnOk returns a tuple with the AgentLastLoggedInUpn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentLastLoggedInUpnOk() (*string, bool) {
	if o == nil || IsNil(o.AgentLastLoggedInUpn) {
		return nil, false
	}
	return o.AgentLastLoggedInUpn, true
}

// HasAgentLastLoggedInUpn returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentLastLoggedInUpn() bool {
	if o != nil && !IsNil(o.AgentLastLoggedInUpn) {
		return true
	}

	return false
}

// SetAgentLastLoggedInUpn gets a reference to the given string and assigns it to the AgentLastLoggedInUpn field.
func (o *ClientAgentThreatDetectionInfo) SetAgentLastLoggedInUpn(v string) {
	o.AgentLastLoggedInUpn = &v
}

// GetAgentLastLoggedInUserMail returns the AgentLastLoggedInUserMail field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentLastLoggedInUserMail() string {
	if o == nil || IsNil(o.AgentLastLoggedInUserMail) {
		var ret string
		return ret
	}
	return *o.AgentLastLoggedInUserMail
}

// GetAgentLastLoggedInUserMailOk returns a tuple with the AgentLastLoggedInUserMail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentLastLoggedInUserMailOk() (*string, bool) {
	if o == nil || IsNil(o.AgentLastLoggedInUserMail) {
		return nil, false
	}
	return o.AgentLastLoggedInUserMail, true
}

// HasAgentLastLoggedInUserMail returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentLastLoggedInUserMail() bool {
	if o != nil && !IsNil(o.AgentLastLoggedInUserMail) {
		return true
	}

	return false
}

// SetAgentLastLoggedInUserMail gets a reference to the given string and assigns it to the AgentLastLoggedInUserMail field.
func (o *ClientAgentThreatDetectionInfo) SetAgentLastLoggedInUserMail(v string) {
	o.AgentLastLoggedInUserMail = &v
}

// GetAgentLastLoggedInUserName returns the AgentLastLoggedInUserName field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentLastLoggedInUserName() string {
	if o == nil || IsNil(o.AgentLastLoggedInUserName) {
		var ret string
		return ret
	}
	return *o.AgentLastLoggedInUserName
}

// GetAgentLastLoggedInUserNameOk returns a tuple with the AgentLastLoggedInUserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentLastLoggedInUserNameOk() (*string, bool) {
	if o == nil || IsNil(o.AgentLastLoggedInUserName) {
		return nil, false
	}
	return o.AgentLastLoggedInUserName, true
}

// HasAgentLastLoggedInUserName returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentLastLoggedInUserName() bool {
	if o != nil && !IsNil(o.AgentLastLoggedInUserName) {
		return true
	}

	return false
}

// SetAgentLastLoggedInUserName gets a reference to the given string and assigns it to the AgentLastLoggedInUserName field.
func (o *ClientAgentThreatDetectionInfo) SetAgentLastLoggedInUserName(v string) {
	o.AgentLastLoggedInUserName = &v
}

// GetAgentMitigationMode returns the AgentMitigationMode field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentMitigationMode() string {
	if o == nil || IsNil(o.AgentMitigationMode) {
		var ret string
		return ret
	}
	return *o.AgentMitigationMode
}

// GetAgentMitigationModeOk returns a tuple with the AgentMitigationMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentMitigationModeOk() (*string, bool) {
	if o == nil || IsNil(o.AgentMitigationMode) {
		return nil, false
	}
	return o.AgentMitigationMode, true
}

// HasAgentMitigationMode returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentMitigationMode() bool {
	if o != nil && !IsNil(o.AgentMitigationMode) {
		return true
	}

	return false
}

// SetAgentMitigationMode gets a reference to the given string and assigns it to the AgentMitigationMode field.
func (o *ClientAgentThreatDetectionInfo) SetAgentMitigationMode(v string) {
	o.AgentMitigationMode = &v
}

// GetAgentOsName returns the AgentOsName field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentOsName() string {
	if o == nil || IsNil(o.AgentOsName) {
		var ret string
		return ret
	}
	return *o.AgentOsName
}

// GetAgentOsNameOk returns a tuple with the AgentOsName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentOsNameOk() (*string, bool) {
	if o == nil || IsNil(o.AgentOsName) {
		return nil, false
	}
	return o.AgentOsName, true
}

// HasAgentOsName returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentOsName() bool {
	if o != nil && !IsNil(o.AgentOsName) {
		return true
	}

	return false
}

// SetAgentOsName gets a reference to the given string and assigns it to the AgentOsName field.
func (o *ClientAgentThreatDetectionInfo) SetAgentOsName(v string) {
	o.AgentOsName = &v
}

// GetAgentOsRevision returns the AgentOsRevision field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentOsRevision() string {
	if o == nil || IsNil(o.AgentOsRevision) {
		var ret string
		return ret
	}
	return *o.AgentOsRevision
}

// GetAgentOsRevisionOk returns a tuple with the AgentOsRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentOsRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.AgentOsRevision) {
		return nil, false
	}
	return o.AgentOsRevision, true
}

// HasAgentOsRevision returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentOsRevision() bool {
	if o != nil && !IsNil(o.AgentOsRevision) {
		return true
	}

	return false
}

// SetAgentOsRevision gets a reference to the given string and assigns it to the AgentOsRevision field.
func (o *ClientAgentThreatDetectionInfo) SetAgentOsRevision(v string) {
	o.AgentOsRevision = &v
}

// GetAgentRegisteredAt returns the AgentRegisteredAt field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentRegisteredAt() string {
	if o == nil || IsNil(o.AgentRegisteredAt) {
		var ret string
		return ret
	}
	return *o.AgentRegisteredAt
}

// GetAgentRegisteredAtOk returns a tuple with the AgentRegisteredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentRegisteredAtOk() (*string, bool) {
	if o == nil || IsNil(o.AgentRegisteredAt) {
		return nil, false
	}
	return o.AgentRegisteredAt, true
}

// HasAgentRegisteredAt returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentRegisteredAt() bool {
	if o != nil && !IsNil(o.AgentRegisteredAt) {
		return true
	}

	return false
}

// SetAgentRegisteredAt gets a reference to the given string and assigns it to the AgentRegisteredAt field.
func (o *ClientAgentThreatDetectionInfo) SetAgentRegisteredAt(v string) {
	o.AgentRegisteredAt = &v
}

// GetAgentUuid returns the AgentUuid field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentUuid() string {
	if o == nil || IsNil(o.AgentUuid) {
		var ret string
		return ret
	}
	return *o.AgentUuid
}

// GetAgentUuidOk returns a tuple with the AgentUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentUuidOk() (*string, bool) {
	if o == nil || IsNil(o.AgentUuid) {
		return nil, false
	}
	return o.AgentUuid, true
}

// HasAgentUuid returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentUuid() bool {
	if o != nil && !IsNil(o.AgentUuid) {
		return true
	}

	return false
}

// SetAgentUuid gets a reference to the given string and assigns it to the AgentUuid field.
func (o *ClientAgentThreatDetectionInfo) SetAgentUuid(v string) {
	o.AgentUuid = &v
}

// GetAgentVersion returns the AgentVersion field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAgentVersion() string {
	if o == nil || IsNil(o.AgentVersion) {
		var ret string
		return ret
	}
	return *o.AgentVersion
}

// GetAgentVersionOk returns a tuple with the AgentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAgentVersionOk() (*string, bool) {
	if o == nil || IsNil(o.AgentVersion) {
		return nil, false
	}
	return o.AgentVersion, true
}

// HasAgentVersion returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAgentVersion() bool {
	if o != nil && !IsNil(o.AgentVersion) {
		return true
	}

	return false
}

// SetAgentVersion gets a reference to the given string and assigns it to the AgentVersion field.
func (o *ClientAgentThreatDetectionInfo) SetAgentVersion(v string) {
	o.AgentVersion = &v
}

// GetAssetVersion returns the AssetVersion field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetAssetVersion() string {
	if o == nil || IsNil(o.AssetVersion) {
		var ret string
		return ret
	}
	return *o.AssetVersion
}

// GetAssetVersionOk returns a tuple with the AssetVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetAssetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.AssetVersion) {
		return nil, false
	}
	return o.AssetVersion, true
}

// HasAssetVersion returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasAssetVersion() bool {
	if o != nil && !IsNil(o.AssetVersion) {
		return true
	}

	return false
}

// SetAssetVersion gets a reference to the given string and assigns it to the AssetVersion field.
func (o *ClientAgentThreatDetectionInfo) SetAssetVersion(v string) {
	o.AssetVersion = &v
}

// GetCloudProviders returns the CloudProviders field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetCloudProviders() map[string]ClientDetectionInfoCloudProvider {
	if o == nil || IsNil(o.CloudProviders) {
		var ret map[string]ClientDetectionInfoCloudProvider
		return ret
	}
	return *o.CloudProviders
}

// GetCloudProvidersOk returns a tuple with the CloudProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetCloudProvidersOk() (*map[string]ClientDetectionInfoCloudProvider, bool) {
	if o == nil || IsNil(o.CloudProviders) {
		return nil, false
	}
	return o.CloudProviders, true
}

// HasCloudProviders returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasCloudProviders() bool {
	if o != nil && !IsNil(o.CloudProviders) {
		return true
	}

	return false
}

// SetCloudProviders gets a reference to the given map[string]ClientDetectionInfoCloudProvider and assigns it to the CloudProviders field.
func (o *ClientAgentThreatDetectionInfo) SetCloudProviders(v map[string]ClientDetectionInfoCloudProvider) {
	o.CloudProviders = &v
}

// GetExternalIp returns the ExternalIp field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetExternalIp() string {
	if o == nil || IsNil(o.ExternalIp) {
		var ret string
		return ret
	}
	return *o.ExternalIp
}

// GetExternalIpOk returns a tuple with the ExternalIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetExternalIpOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalIp) {
		return nil, false
	}
	return o.ExternalIp, true
}

// HasExternalIp returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasExternalIp() bool {
	if o != nil && !IsNil(o.ExternalIp) {
		return true
	}

	return false
}

// SetExternalIp gets a reference to the given string and assigns it to the ExternalIp field.
func (o *ClientAgentThreatDetectionInfo) SetExternalIp(v string) {
	o.ExternalIp = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetGroupId() string {
	if o == nil || IsNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *ClientAgentThreatDetectionInfo) SetGroupId(v string) {
	o.GroupId = &v
}

// GetGroupName returns the GroupName field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetGroupName() string {
	if o == nil || IsNil(o.GroupName) {
		var ret string
		return ret
	}
	return *o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.GroupName) {
		return nil, false
	}
	return o.GroupName, true
}

// HasGroupName returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasGroupName() bool {
	if o != nil && !IsNil(o.GroupName) {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given string and assigns it to the GroupName field.
func (o *ClientAgentThreatDetectionInfo) SetGroupName(v string) {
	o.GroupName = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *ClientAgentThreatDetectionInfo) SetSiteId(v string) {
	o.SiteId = &v
}

// GetSiteName returns the SiteName field value if set, zero value otherwise.
func (o *ClientAgentThreatDetectionInfo) GetSiteName() string {
	if o == nil || IsNil(o.SiteName) {
		var ret string
		return ret
	}
	return *o.SiteName
}

// GetSiteNameOk returns a tuple with the SiteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientAgentThreatDetectionInfo) GetSiteNameOk() (*string, bool) {
	if o == nil || IsNil(o.SiteName) {
		return nil, false
	}
	return o.SiteName, true
}

// HasSiteName returns a boolean if a field has been set.
func (o *ClientAgentThreatDetectionInfo) HasSiteName() bool {
	if o != nil && !IsNil(o.SiteName) {
		return true
	}

	return false
}

// SetSiteName gets a reference to the given string and assigns it to the SiteName field.
func (o *ClientAgentThreatDetectionInfo) SetSiteName(v string) {
	o.SiteName = &v
}

func (o ClientAgentThreatDetectionInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientAgentThreatDetectionInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.AccountName) {
		toSerialize["accountName"] = o.AccountName
	}
	if !IsNil(o.AgentDetectionState) {
		toSerialize["agentDetectionState"] = o.AgentDetectionState
	}
	if !IsNil(o.AgentDomain) {
		toSerialize["agentDomain"] = o.AgentDomain
	}
	if !IsNil(o.AgentIpV4) {
		toSerialize["agentIpV4"] = o.AgentIpV4
	}
	if !IsNil(o.AgentIpV6) {
		toSerialize["agentIpV6"] = o.AgentIpV6
	}
	if !IsNil(o.AgentLastLoggedInUpn) {
		toSerialize["agentLastLoggedInUpn"] = o.AgentLastLoggedInUpn
	}
	if !IsNil(o.AgentLastLoggedInUserMail) {
		toSerialize["agentLastLoggedInUserMail"] = o.AgentLastLoggedInUserMail
	}
	if !IsNil(o.AgentLastLoggedInUserName) {
		toSerialize["agentLastLoggedInUserName"] = o.AgentLastLoggedInUserName
	}
	if !IsNil(o.AgentMitigationMode) {
		toSerialize["agentMitigationMode"] = o.AgentMitigationMode
	}
	if !IsNil(o.AgentOsName) {
		toSerialize["agentOsName"] = o.AgentOsName
	}
	if !IsNil(o.AgentOsRevision) {
		toSerialize["agentOsRevision"] = o.AgentOsRevision
	}
	if !IsNil(o.AgentRegisteredAt) {
		toSerialize["agentRegisteredAt"] = o.AgentRegisteredAt
	}
	if !IsNil(o.AgentUuid) {
		toSerialize["agentUuid"] = o.AgentUuid
	}
	if !IsNil(o.AgentVersion) {
		toSerialize["agentVersion"] = o.AgentVersion
	}
	if !IsNil(o.AssetVersion) {
		toSerialize["assetVersion"] = o.AssetVersion
	}
	if !IsNil(o.CloudProviders) {
		toSerialize["cloudProviders"] = o.CloudProviders
	}
	if !IsNil(o.ExternalIp) {
		toSerialize["externalIp"] = o.ExternalIp
	}
	if !IsNil(o.GroupId) {
		toSerialize["groupId"] = o.GroupId
	}
	if !IsNil(o.GroupName) {
		toSerialize["groupName"] = o.GroupName
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.SiteName) {
		toSerialize["siteName"] = o.SiteName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClientAgentThreatDetectionInfo) UnmarshalJSON(data []byte) (err error) {
	varClientAgentThreatDetectionInfo := _ClientAgentThreatDetectionInfo{}

	err = json.Unmarshal(data, &varClientAgentThreatDetectionInfo)

	if err != nil {
		return err
	}

	*o = ClientAgentThreatDetectionInfo(varClientAgentThreatDetectionInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "accountId")
		delete(additionalProperties, "accountName")
		delete(additionalProperties, "agentDetectionState")
		delete(additionalProperties, "agentDomain")
		delete(additionalProperties, "agentIpV4")
		delete(additionalProperties, "agentIpV6")
		delete(additionalProperties, "agentLastLoggedInUpn")
		delete(additionalProperties, "agentLastLoggedInUserMail")
		delete(additionalProperties, "agentLastLoggedInUserName")
		delete(additionalProperties, "agentMitigationMode")
		delete(additionalProperties, "agentOsName")
		delete(additionalProperties, "agentOsRevision")
		delete(additionalProperties, "agentRegisteredAt")
		delete(additionalProperties, "agentUuid")
		delete(additionalProperties, "agentVersion")
		delete(additionalProperties, "assetVersion")
		delete(additionalProperties, "cloudProviders")
		delete(additionalProperties, "externalIp")
		delete(additionalProperties, "groupId")
		delete(additionalProperties, "groupName")
		delete(additionalProperties, "siteId")
		delete(additionalProperties, "siteName")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClientAgentThreatDetectionInfo struct {
	value *ClientAgentThreatDetectionInfo
	isSet bool
}

func (v NullableClientAgentThreatDetectionInfo) Get() *ClientAgentThreatDetectionInfo {
	return v.value
}

func (v *NullableClientAgentThreatDetectionInfo) Set(val *ClientAgentThreatDetectionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableClientAgentThreatDetectionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableClientAgentThreatDetectionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientAgentThreatDetectionInfo(val *ClientAgentThreatDetectionInfo) *NullableClientAgentThreatDetectionInfo {
	return &NullableClientAgentThreatDetectionInfo{value: val, isSet: true}
}

func (v NullableClientAgentThreatDetectionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientAgentThreatDetectionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
