/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the DmCheckinServiceStatusErrorReason type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DmCheckinServiceStatusErrorReason{}

// DmCheckinServiceStatusErrorReason struct for DmCheckinServiceStatusErrorReason
type DmCheckinServiceStatusErrorReason struct {
	Code                 *string                `json:"code,omitempty"`
	Description          *string                `json:"description,omitempty"`
	Details              map[string]interface{} `json:"details,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DmCheckinServiceStatusErrorReason DmCheckinServiceStatusErrorReason

// NewDmCheckinServiceStatusErrorReason instantiates a new DmCheckinServiceStatusErrorReason object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDmCheckinServiceStatusErrorReason() *DmCheckinServiceStatusErrorReason {
	this := DmCheckinServiceStatusErrorReason{}
	return &this
}

// NewDmCheckinServiceStatusErrorReasonWithDefaults instantiates a new DmCheckinServiceStatusErrorReason object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDmCheckinServiceStatusErrorReasonWithDefaults() *DmCheckinServiceStatusErrorReason {
	this := DmCheckinServiceStatusErrorReason{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *DmCheckinServiceStatusErrorReason) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DmCheckinServiceStatusErrorReason) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *DmCheckinServiceStatusErrorReason) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *DmCheckinServiceStatusErrorReason) SetCode(v string) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DmCheckinServiceStatusErrorReason) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DmCheckinServiceStatusErrorReason) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DmCheckinServiceStatusErrorReason) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DmCheckinServiceStatusErrorReason) SetDescription(v string) {
	o.Description = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *DmCheckinServiceStatusErrorReason) GetDetails() map[string]interface{} {
	if o == nil || IsNil(o.Details) {
		var ret map[string]interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DmCheckinServiceStatusErrorReason) GetDetailsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return map[string]interface{}{}, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *DmCheckinServiceStatusErrorReason) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given map[string]interface{} and assigns it to the Details field.
func (o *DmCheckinServiceStatusErrorReason) SetDetails(v map[string]interface{}) {
	o.Details = v
}

func (o DmCheckinServiceStatusErrorReason) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DmCheckinServiceStatusErrorReason) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DmCheckinServiceStatusErrorReason) UnmarshalJSON(data []byte) (err error) {
	varDmCheckinServiceStatusErrorReason := _DmCheckinServiceStatusErrorReason{}

	err = json.Unmarshal(data, &varDmCheckinServiceStatusErrorReason)

	if err != nil {
		return err
	}

	*o = DmCheckinServiceStatusErrorReason(varDmCheckinServiceStatusErrorReason)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "description")
		delete(additionalProperties, "details")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDmCheckinServiceStatusErrorReason struct {
	value *DmCheckinServiceStatusErrorReason
	isSet bool
}

func (v NullableDmCheckinServiceStatusErrorReason) Get() *DmCheckinServiceStatusErrorReason {
	return v.value
}

func (v *NullableDmCheckinServiceStatusErrorReason) Set(val *DmCheckinServiceStatusErrorReason) {
	v.value = val
	v.isSet = true
}

func (v NullableDmCheckinServiceStatusErrorReason) IsSet() bool {
	return v.isSet
}

func (v *NullableDmCheckinServiceStatusErrorReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDmCheckinServiceStatusErrorReason(val *DmCheckinServiceStatusErrorReason) *NullableDmCheckinServiceStatusErrorReason {
	return &NullableDmCheckinServiceStatusErrorReason{value: val, isSet: true}
}

func (v NullableDmCheckinServiceStatusErrorReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDmCheckinServiceStatusErrorReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
