/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the SoftwareUpdatesServiceOsUpdateCatalogEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SoftwareUpdatesServiceOsUpdateCatalogEntry{}

// SoftwareUpdatesServiceOsUpdateCatalogEntry struct for SoftwareUpdatesServiceOsUpdateCatalogEntry
type SoftwareUpdatesServiceOsUpdateCatalogEntry struct {
	Build                *string  `json:"Build,omitempty"`
	ExpirationDate       *string  `json:"ExpirationDate,omitempty"`
	PostingDate          *string  `json:"PostingDate,omitempty"`
	ProductVersion       *string  `json:"ProductVersion,omitempty"`
	SupportedDevices     []string `json:"SupportedDevices,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SoftwareUpdatesServiceOsUpdateCatalogEntry SoftwareUpdatesServiceOsUpdateCatalogEntry

// NewSoftwareUpdatesServiceOsUpdateCatalogEntry instantiates a new SoftwareUpdatesServiceOsUpdateCatalogEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoftwareUpdatesServiceOsUpdateCatalogEntry() *SoftwareUpdatesServiceOsUpdateCatalogEntry {
	this := SoftwareUpdatesServiceOsUpdateCatalogEntry{}
	return &this
}

// NewSoftwareUpdatesServiceOsUpdateCatalogEntryWithDefaults instantiates a new SoftwareUpdatesServiceOsUpdateCatalogEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoftwareUpdatesServiceOsUpdateCatalogEntryWithDefaults() *SoftwareUpdatesServiceOsUpdateCatalogEntry {
	this := SoftwareUpdatesServiceOsUpdateCatalogEntry{}
	return &this
}

// GetBuild returns the Build field value if set, zero value otherwise.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) GetBuild() string {
	if o == nil || IsNil(o.Build) {
		var ret string
		return ret
	}
	return *o.Build
}

// GetBuildOk returns a tuple with the Build field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) GetBuildOk() (*string, bool) {
	if o == nil || IsNil(o.Build) {
		return nil, false
	}
	return o.Build, true
}

// HasBuild returns a boolean if a field has been set.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) HasBuild() bool {
	if o != nil && !IsNil(o.Build) {
		return true
	}

	return false
}

// SetBuild gets a reference to the given string and assigns it to the Build field.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) SetBuild(v string) {
	o.Build = &v
}

// GetExpirationDate returns the ExpirationDate field value if set, zero value otherwise.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) GetExpirationDate() string {
	if o == nil || IsNil(o.ExpirationDate) {
		var ret string
		return ret
	}
	return *o.ExpirationDate
}

// GetExpirationDateOk returns a tuple with the ExpirationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) GetExpirationDateOk() (*string, bool) {
	if o == nil || IsNil(o.ExpirationDate) {
		return nil, false
	}
	return o.ExpirationDate, true
}

// HasExpirationDate returns a boolean if a field has been set.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) HasExpirationDate() bool {
	if o != nil && !IsNil(o.ExpirationDate) {
		return true
	}

	return false
}

// SetExpirationDate gets a reference to the given string and assigns it to the ExpirationDate field.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) SetExpirationDate(v string) {
	o.ExpirationDate = &v
}

// GetPostingDate returns the PostingDate field value if set, zero value otherwise.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) GetPostingDate() string {
	if o == nil || IsNil(o.PostingDate) {
		var ret string
		return ret
	}
	return *o.PostingDate
}

// GetPostingDateOk returns a tuple with the PostingDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) GetPostingDateOk() (*string, bool) {
	if o == nil || IsNil(o.PostingDate) {
		return nil, false
	}
	return o.PostingDate, true
}

// HasPostingDate returns a boolean if a field has been set.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) HasPostingDate() bool {
	if o != nil && !IsNil(o.PostingDate) {
		return true
	}

	return false
}

// SetPostingDate gets a reference to the given string and assigns it to the PostingDate field.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) SetPostingDate(v string) {
	o.PostingDate = &v
}

// GetProductVersion returns the ProductVersion field value if set, zero value otherwise.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) GetProductVersion() string {
	if o == nil || IsNil(o.ProductVersion) {
		var ret string
		return ret
	}
	return *o.ProductVersion
}

// GetProductVersionOk returns a tuple with the ProductVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) GetProductVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ProductVersion) {
		return nil, false
	}
	return o.ProductVersion, true
}

// HasProductVersion returns a boolean if a field has been set.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) HasProductVersion() bool {
	if o != nil && !IsNil(o.ProductVersion) {
		return true
	}

	return false
}

// SetProductVersion gets a reference to the given string and assigns it to the ProductVersion field.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) SetProductVersion(v string) {
	o.ProductVersion = &v
}

// GetSupportedDevices returns the SupportedDevices field value if set, zero value otherwise.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) GetSupportedDevices() []string {
	if o == nil || IsNil(o.SupportedDevices) {
		var ret []string
		return ret
	}
	return o.SupportedDevices
}

// GetSupportedDevicesOk returns a tuple with the SupportedDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) GetSupportedDevicesOk() ([]string, bool) {
	if o == nil || IsNil(o.SupportedDevices) {
		return nil, false
	}
	return o.SupportedDevices, true
}

// HasSupportedDevices returns a boolean if a field has been set.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) HasSupportedDevices() bool {
	if o != nil && !IsNil(o.SupportedDevices) {
		return true
	}

	return false
}

// SetSupportedDevices gets a reference to the given []string and assigns it to the SupportedDevices field.
func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) SetSupportedDevices(v []string) {
	o.SupportedDevices = v
}

func (o SoftwareUpdatesServiceOsUpdateCatalogEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SoftwareUpdatesServiceOsUpdateCatalogEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Build) {
		toSerialize["Build"] = o.Build
	}
	if !IsNil(o.ExpirationDate) {
		toSerialize["ExpirationDate"] = o.ExpirationDate
	}
	if !IsNil(o.PostingDate) {
		toSerialize["PostingDate"] = o.PostingDate
	}
	if !IsNil(o.ProductVersion) {
		toSerialize["ProductVersion"] = o.ProductVersion
	}
	if !IsNil(o.SupportedDevices) {
		toSerialize["SupportedDevices"] = o.SupportedDevices
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SoftwareUpdatesServiceOsUpdateCatalogEntry) UnmarshalJSON(data []byte) (err error) {
	varSoftwareUpdatesServiceOsUpdateCatalogEntry := _SoftwareUpdatesServiceOsUpdateCatalogEntry{}

	err = json.Unmarshal(data, &varSoftwareUpdatesServiceOsUpdateCatalogEntry)

	if err != nil {
		return err
	}

	*o = SoftwareUpdatesServiceOsUpdateCatalogEntry(varSoftwareUpdatesServiceOsUpdateCatalogEntry)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Build")
		delete(additionalProperties, "ExpirationDate")
		delete(additionalProperties, "PostingDate")
		delete(additionalProperties, "ProductVersion")
		delete(additionalProperties, "SupportedDevices")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSoftwareUpdatesServiceOsUpdateCatalogEntry struct {
	value *SoftwareUpdatesServiceOsUpdateCatalogEntry
	isSet bool
}

func (v NullableSoftwareUpdatesServiceOsUpdateCatalogEntry) Get() *SoftwareUpdatesServiceOsUpdateCatalogEntry {
	return v.value
}

func (v *NullableSoftwareUpdatesServiceOsUpdateCatalogEntry) Set(val *SoftwareUpdatesServiceOsUpdateCatalogEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableSoftwareUpdatesServiceOsUpdateCatalogEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableSoftwareUpdatesServiceOsUpdateCatalogEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoftwareUpdatesServiceOsUpdateCatalogEntry(val *SoftwareUpdatesServiceOsUpdateCatalogEntry) *NullableSoftwareUpdatesServiceOsUpdateCatalogEntry {
	return &NullableSoftwareUpdatesServiceOsUpdateCatalogEntry{value: val, isSet: true}
}

func (v NullableSoftwareUpdatesServiceOsUpdateCatalogEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoftwareUpdatesServiceOsUpdateCatalogEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
