/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
	"fmt"
)

// checks if the VariableEntitiesPolicyValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VariableEntitiesPolicyValue{}

// VariableEntitiesPolicyValue struct for VariableEntitiesPolicyValue
type VariableEntitiesPolicyValue struct {
	PolicyId             string                 `json:"policy_id"`
	Value                map[string]interface{} `json:"value"`
	AdditionalProperties map[string]interface{}
}

type _VariableEntitiesPolicyValue VariableEntitiesPolicyValue

// NewVariableEntitiesPolicyValue instantiates a new VariableEntitiesPolicyValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVariableEntitiesPolicyValue(policyId string, value map[string]interface{}) *VariableEntitiesPolicyValue {
	this := VariableEntitiesPolicyValue{}
	this.PolicyId = policyId
	this.Value = value
	return &this
}

// NewVariableEntitiesPolicyValueWithDefaults instantiates a new VariableEntitiesPolicyValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVariableEntitiesPolicyValueWithDefaults() *VariableEntitiesPolicyValue {
	this := VariableEntitiesPolicyValue{}
	return &this
}

// GetPolicyId returns the PolicyId field value
func (o *VariableEntitiesPolicyValue) GetPolicyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PolicyId
}

// GetPolicyIdOk returns a tuple with the PolicyId field value
// and a boolean to check if the value has been set.
func (o *VariableEntitiesPolicyValue) GetPolicyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PolicyId, true
}

// SetPolicyId sets field value
func (o *VariableEntitiesPolicyValue) SetPolicyId(v string) {
	o.PolicyId = v
}

// GetValue returns the Value field value
func (o *VariableEntitiesPolicyValue) GetValue() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *VariableEntitiesPolicyValue) GetValueOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *VariableEntitiesPolicyValue) SetValue(v map[string]interface{}) {
	o.Value = v
}

func (o VariableEntitiesPolicyValue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VariableEntitiesPolicyValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy_id"] = o.PolicyId
	toSerialize["value"] = o.Value

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VariableEntitiesPolicyValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"policy_id",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVariableEntitiesPolicyValue := _VariableEntitiesPolicyValue{}

	err = json.Unmarshal(data, &varVariableEntitiesPolicyValue)

	if err != nil {
		return err
	}

	*o = VariableEntitiesPolicyValue(varVariableEntitiesPolicyValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "policy_id")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVariableEntitiesPolicyValue struct {
	value *VariableEntitiesPolicyValue
	isSet bool
}

func (v NullableVariableEntitiesPolicyValue) Get() *VariableEntitiesPolicyValue {
	return v.value
}

func (v *NullableVariableEntitiesPolicyValue) Set(val *VariableEntitiesPolicyValue) {
	v.value = val
	v.isSet = true
}

func (v NullableVariableEntitiesPolicyValue) IsSet() bool {
	return v.isSet
}

func (v *NullableVariableEntitiesPolicyValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVariableEntitiesPolicyValue(val *VariableEntitiesPolicyValue) *NullableVariableEntitiesPolicyValue {
	return &NullableVariableEntitiesPolicyValue{value: val, isSet: true}
}

func (v NullableVariableEntitiesPolicyValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVariableEntitiesPolicyValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
