/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the ClientMigrationJobDevices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientMigrationJobDevices{}

// ClientMigrationJobDevices struct for ClientMigrationJobDevices
type ClientMigrationJobDevices struct {
	DeviceUuid             *string                   `json:"device_uuid,omitempty"`
	Error                  *string                   `json:"error,omitempty"`
	JobId                  *string                   `json:"job_id,omitempty"`
	NewAgentId             *string                   `json:"new_agent_id,omitempty"`
	NewLocationPolicyId    *string                   `json:"new_location_policy_id,omitempty"`
	NewOrganizationId      *string                   `json:"new_organization_id,omitempty"`
	SerialNumber           *string                   `json:"serial_number,omitempty"`
	SourceAgentId          *string                   `json:"source_agent_id,omitempty"`
	SourceLocationPolicyId *string                   `json:"source_location_policy_id,omitempty"`
	SourceOrganizationId   *string                   `json:"source_organization_id,omitempty"`
	Status                 *ClientMigrationJobStatus `json:"status,omitempty"`
	UpdatedAt              *string                   `json:"updated_at,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _ClientMigrationJobDevices ClientMigrationJobDevices

// NewClientMigrationJobDevices instantiates a new ClientMigrationJobDevices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientMigrationJobDevices() *ClientMigrationJobDevices {
	this := ClientMigrationJobDevices{}
	return &this
}

// NewClientMigrationJobDevicesWithDefaults instantiates a new ClientMigrationJobDevices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientMigrationJobDevicesWithDefaults() *ClientMigrationJobDevices {
	this := ClientMigrationJobDevices{}
	return &this
}

// GetDeviceUuid returns the DeviceUuid field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetDeviceUuid() string {
	if o == nil || IsNil(o.DeviceUuid) {
		var ret string
		return ret
	}
	return *o.DeviceUuid
}

// GetDeviceUuidOk returns a tuple with the DeviceUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetDeviceUuidOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceUuid) {
		return nil, false
	}
	return o.DeviceUuid, true
}

// HasDeviceUuid returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasDeviceUuid() bool {
	if o != nil && !IsNil(o.DeviceUuid) {
		return true
	}

	return false
}

// SetDeviceUuid gets a reference to the given string and assigns it to the DeviceUuid field.
func (o *ClientMigrationJobDevices) SetDeviceUuid(v string) {
	o.DeviceUuid = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *ClientMigrationJobDevices) SetError(v string) {
	o.Error = &v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *ClientMigrationJobDevices) SetJobId(v string) {
	o.JobId = &v
}

// GetNewAgentId returns the NewAgentId field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetNewAgentId() string {
	if o == nil || IsNil(o.NewAgentId) {
		var ret string
		return ret
	}
	return *o.NewAgentId
}

// GetNewAgentIdOk returns a tuple with the NewAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetNewAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.NewAgentId) {
		return nil, false
	}
	return o.NewAgentId, true
}

// HasNewAgentId returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasNewAgentId() bool {
	if o != nil && !IsNil(o.NewAgentId) {
		return true
	}

	return false
}

// SetNewAgentId gets a reference to the given string and assigns it to the NewAgentId field.
func (o *ClientMigrationJobDevices) SetNewAgentId(v string) {
	o.NewAgentId = &v
}

// GetNewLocationPolicyId returns the NewLocationPolicyId field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetNewLocationPolicyId() string {
	if o == nil || IsNil(o.NewLocationPolicyId) {
		var ret string
		return ret
	}
	return *o.NewLocationPolicyId
}

// GetNewLocationPolicyIdOk returns a tuple with the NewLocationPolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetNewLocationPolicyIdOk() (*string, bool) {
	if o == nil || IsNil(o.NewLocationPolicyId) {
		return nil, false
	}
	return o.NewLocationPolicyId, true
}

// HasNewLocationPolicyId returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasNewLocationPolicyId() bool {
	if o != nil && !IsNil(o.NewLocationPolicyId) {
		return true
	}

	return false
}

// SetNewLocationPolicyId gets a reference to the given string and assigns it to the NewLocationPolicyId field.
func (o *ClientMigrationJobDevices) SetNewLocationPolicyId(v string) {
	o.NewLocationPolicyId = &v
}

// GetNewOrganizationId returns the NewOrganizationId field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetNewOrganizationId() string {
	if o == nil || IsNil(o.NewOrganizationId) {
		var ret string
		return ret
	}
	return *o.NewOrganizationId
}

// GetNewOrganizationIdOk returns a tuple with the NewOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetNewOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.NewOrganizationId) {
		return nil, false
	}
	return o.NewOrganizationId, true
}

// HasNewOrganizationId returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasNewOrganizationId() bool {
	if o != nil && !IsNil(o.NewOrganizationId) {
		return true
	}

	return false
}

// SetNewOrganizationId gets a reference to the given string and assigns it to the NewOrganizationId field.
func (o *ClientMigrationJobDevices) SetNewOrganizationId(v string) {
	o.NewOrganizationId = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetSerialNumber() string {
	if o == nil || IsNil(o.SerialNumber) {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SerialNumber) {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasSerialNumber() bool {
	if o != nil && !IsNil(o.SerialNumber) {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *ClientMigrationJobDevices) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

// GetSourceAgentId returns the SourceAgentId field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetSourceAgentId() string {
	if o == nil || IsNil(o.SourceAgentId) {
		var ret string
		return ret
	}
	return *o.SourceAgentId
}

// GetSourceAgentIdOk returns a tuple with the SourceAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetSourceAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceAgentId) {
		return nil, false
	}
	return o.SourceAgentId, true
}

// HasSourceAgentId returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasSourceAgentId() bool {
	if o != nil && !IsNil(o.SourceAgentId) {
		return true
	}

	return false
}

// SetSourceAgentId gets a reference to the given string and assigns it to the SourceAgentId field.
func (o *ClientMigrationJobDevices) SetSourceAgentId(v string) {
	o.SourceAgentId = &v
}

// GetSourceLocationPolicyId returns the SourceLocationPolicyId field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetSourceLocationPolicyId() string {
	if o == nil || IsNil(o.SourceLocationPolicyId) {
		var ret string
		return ret
	}
	return *o.SourceLocationPolicyId
}

// GetSourceLocationPolicyIdOk returns a tuple with the SourceLocationPolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetSourceLocationPolicyIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceLocationPolicyId) {
		return nil, false
	}
	return o.SourceLocationPolicyId, true
}

// HasSourceLocationPolicyId returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasSourceLocationPolicyId() bool {
	if o != nil && !IsNil(o.SourceLocationPolicyId) {
		return true
	}

	return false
}

// SetSourceLocationPolicyId gets a reference to the given string and assigns it to the SourceLocationPolicyId field.
func (o *ClientMigrationJobDevices) SetSourceLocationPolicyId(v string) {
	o.SourceLocationPolicyId = &v
}

// GetSourceOrganizationId returns the SourceOrganizationId field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetSourceOrganizationId() string {
	if o == nil || IsNil(o.SourceOrganizationId) {
		var ret string
		return ret
	}
	return *o.SourceOrganizationId
}

// GetSourceOrganizationIdOk returns a tuple with the SourceOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetSourceOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceOrganizationId) {
		return nil, false
	}
	return o.SourceOrganizationId, true
}

// HasSourceOrganizationId returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasSourceOrganizationId() bool {
	if o != nil && !IsNil(o.SourceOrganizationId) {
		return true
	}

	return false
}

// SetSourceOrganizationId gets a reference to the given string and assigns it to the SourceOrganizationId field.
func (o *ClientMigrationJobDevices) SetSourceOrganizationId(v string) {
	o.SourceOrganizationId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetStatus() ClientMigrationJobStatus {
	if o == nil || IsNil(o.Status) {
		var ret ClientMigrationJobStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetStatusOk() (*ClientMigrationJobStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ClientMigrationJobStatus and assigns it to the Status field.
func (o *ClientMigrationJobDevices) SetStatus(v ClientMigrationJobStatus) {
	o.Status = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ClientMigrationJobDevices) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientMigrationJobDevices) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ClientMigrationJobDevices) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ClientMigrationJobDevices) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o ClientMigrationJobDevices) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientMigrationJobDevices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeviceUuid) {
		toSerialize["device_uuid"] = o.DeviceUuid
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.JobId) {
		toSerialize["job_id"] = o.JobId
	}
	if !IsNil(o.NewAgentId) {
		toSerialize["new_agent_id"] = o.NewAgentId
	}
	if !IsNil(o.NewLocationPolicyId) {
		toSerialize["new_location_policy_id"] = o.NewLocationPolicyId
	}
	if !IsNil(o.NewOrganizationId) {
		toSerialize["new_organization_id"] = o.NewOrganizationId
	}
	if !IsNil(o.SerialNumber) {
		toSerialize["serial_number"] = o.SerialNumber
	}
	if !IsNil(o.SourceAgentId) {
		toSerialize["source_agent_id"] = o.SourceAgentId
	}
	if !IsNil(o.SourceLocationPolicyId) {
		toSerialize["source_location_policy_id"] = o.SourceLocationPolicyId
	}
	if !IsNil(o.SourceOrganizationId) {
		toSerialize["source_organization_id"] = o.SourceOrganizationId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClientMigrationJobDevices) UnmarshalJSON(data []byte) (err error) {
	varClientMigrationJobDevices := _ClientMigrationJobDevices{}

	err = json.Unmarshal(data, &varClientMigrationJobDevices)

	if err != nil {
		return err
	}

	*o = ClientMigrationJobDevices(varClientMigrationJobDevices)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "device_uuid")
		delete(additionalProperties, "error")
		delete(additionalProperties, "job_id")
		delete(additionalProperties, "new_agent_id")
		delete(additionalProperties, "new_location_policy_id")
		delete(additionalProperties, "new_organization_id")
		delete(additionalProperties, "serial_number")
		delete(additionalProperties, "source_agent_id")
		delete(additionalProperties, "source_location_policy_id")
		delete(additionalProperties, "source_organization_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClientMigrationJobDevices struct {
	value *ClientMigrationJobDevices
	isSet bool
}

func (v NullableClientMigrationJobDevices) Get() *ClientMigrationJobDevices {
	return v.value
}

func (v *NullableClientMigrationJobDevices) Set(val *ClientMigrationJobDevices) {
	v.value = val
	v.isSet = true
}

func (v NullableClientMigrationJobDevices) IsSet() bool {
	return v.isSet
}

func (v *NullableClientMigrationJobDevices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientMigrationJobDevices(val *ClientMigrationJobDevices) *NullableClientMigrationJobDevices {
	return &NullableClientMigrationJobDevices{value: val, isSet: true}
}

func (v NullableClientMigrationJobDevices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientMigrationJobDevices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
