/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the ClientKubernetesAlertInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientKubernetesAlertInfo{}

// ClientKubernetesAlertInfo struct for ClientKubernetesAlertInfo
type ClientKubernetesAlertInfo struct {
	Cluster              *string `json:"cluster,omitempty"`
	ControllerKind       *string `json:"controllerKind,omitempty"`
	ControllerLabels     *string `json:"controllerLabels,omitempty"`
	ControllerName       *string `json:"controllerName,omitempty"`
	Namespace            *string `json:"namespace,omitempty"`
	NamespaceLabels      *string `json:"namespaceLabels,omitempty"`
	Node                 *string `json:"node,omitempty"`
	Pod                  *string `json:"pod,omitempty"`
	PodLabels            *string `json:"podLabels,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ClientKubernetesAlertInfo ClientKubernetesAlertInfo

// NewClientKubernetesAlertInfo instantiates a new ClientKubernetesAlertInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientKubernetesAlertInfo() *ClientKubernetesAlertInfo {
	this := ClientKubernetesAlertInfo{}
	return &this
}

// NewClientKubernetesAlertInfoWithDefaults instantiates a new ClientKubernetesAlertInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientKubernetesAlertInfoWithDefaults() *ClientKubernetesAlertInfo {
	this := ClientKubernetesAlertInfo{}
	return &this
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *ClientKubernetesAlertInfo) GetCluster() string {
	if o == nil || IsNil(o.Cluster) {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientKubernetesAlertInfo) GetClusterOk() (*string, bool) {
	if o == nil || IsNil(o.Cluster) {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *ClientKubernetesAlertInfo) HasCluster() bool {
	if o != nil && !IsNil(o.Cluster) {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *ClientKubernetesAlertInfo) SetCluster(v string) {
	o.Cluster = &v
}

// GetControllerKind returns the ControllerKind field value if set, zero value otherwise.
func (o *ClientKubernetesAlertInfo) GetControllerKind() string {
	if o == nil || IsNil(o.ControllerKind) {
		var ret string
		return ret
	}
	return *o.ControllerKind
}

// GetControllerKindOk returns a tuple with the ControllerKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientKubernetesAlertInfo) GetControllerKindOk() (*string, bool) {
	if o == nil || IsNil(o.ControllerKind) {
		return nil, false
	}
	return o.ControllerKind, true
}

// HasControllerKind returns a boolean if a field has been set.
func (o *ClientKubernetesAlertInfo) HasControllerKind() bool {
	if o != nil && !IsNil(o.ControllerKind) {
		return true
	}

	return false
}

// SetControllerKind gets a reference to the given string and assigns it to the ControllerKind field.
func (o *ClientKubernetesAlertInfo) SetControllerKind(v string) {
	o.ControllerKind = &v
}

// GetControllerLabels returns the ControllerLabels field value if set, zero value otherwise.
func (o *ClientKubernetesAlertInfo) GetControllerLabels() string {
	if o == nil || IsNil(o.ControllerLabels) {
		var ret string
		return ret
	}
	return *o.ControllerLabels
}

// GetControllerLabelsOk returns a tuple with the ControllerLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientKubernetesAlertInfo) GetControllerLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.ControllerLabels) {
		return nil, false
	}
	return o.ControllerLabels, true
}

// HasControllerLabels returns a boolean if a field has been set.
func (o *ClientKubernetesAlertInfo) HasControllerLabels() bool {
	if o != nil && !IsNil(o.ControllerLabels) {
		return true
	}

	return false
}

// SetControllerLabels gets a reference to the given string and assigns it to the ControllerLabels field.
func (o *ClientKubernetesAlertInfo) SetControllerLabels(v string) {
	o.ControllerLabels = &v
}

// GetControllerName returns the ControllerName field value if set, zero value otherwise.
func (o *ClientKubernetesAlertInfo) GetControllerName() string {
	if o == nil || IsNil(o.ControllerName) {
		var ret string
		return ret
	}
	return *o.ControllerName
}

// GetControllerNameOk returns a tuple with the ControllerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientKubernetesAlertInfo) GetControllerNameOk() (*string, bool) {
	if o == nil || IsNil(o.ControllerName) {
		return nil, false
	}
	return o.ControllerName, true
}

// HasControllerName returns a boolean if a field has been set.
func (o *ClientKubernetesAlertInfo) HasControllerName() bool {
	if o != nil && !IsNil(o.ControllerName) {
		return true
	}

	return false
}

// SetControllerName gets a reference to the given string and assigns it to the ControllerName field.
func (o *ClientKubernetesAlertInfo) SetControllerName(v string) {
	o.ControllerName = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *ClientKubernetesAlertInfo) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientKubernetesAlertInfo) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *ClientKubernetesAlertInfo) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *ClientKubernetesAlertInfo) SetNamespace(v string) {
	o.Namespace = &v
}

// GetNamespaceLabels returns the NamespaceLabels field value if set, zero value otherwise.
func (o *ClientKubernetesAlertInfo) GetNamespaceLabels() string {
	if o == nil || IsNil(o.NamespaceLabels) {
		var ret string
		return ret
	}
	return *o.NamespaceLabels
}

// GetNamespaceLabelsOk returns a tuple with the NamespaceLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientKubernetesAlertInfo) GetNamespaceLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.NamespaceLabels) {
		return nil, false
	}
	return o.NamespaceLabels, true
}

// HasNamespaceLabels returns a boolean if a field has been set.
func (o *ClientKubernetesAlertInfo) HasNamespaceLabels() bool {
	if o != nil && !IsNil(o.NamespaceLabels) {
		return true
	}

	return false
}

// SetNamespaceLabels gets a reference to the given string and assigns it to the NamespaceLabels field.
func (o *ClientKubernetesAlertInfo) SetNamespaceLabels(v string) {
	o.NamespaceLabels = &v
}

// GetNode returns the Node field value if set, zero value otherwise.
func (o *ClientKubernetesAlertInfo) GetNode() string {
	if o == nil || IsNil(o.Node) {
		var ret string
		return ret
	}
	return *o.Node
}

// GetNodeOk returns a tuple with the Node field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientKubernetesAlertInfo) GetNodeOk() (*string, bool) {
	if o == nil || IsNil(o.Node) {
		return nil, false
	}
	return o.Node, true
}

// HasNode returns a boolean if a field has been set.
func (o *ClientKubernetesAlertInfo) HasNode() bool {
	if o != nil && !IsNil(o.Node) {
		return true
	}

	return false
}

// SetNode gets a reference to the given string and assigns it to the Node field.
func (o *ClientKubernetesAlertInfo) SetNode(v string) {
	o.Node = &v
}

// GetPod returns the Pod field value if set, zero value otherwise.
func (o *ClientKubernetesAlertInfo) GetPod() string {
	if o == nil || IsNil(o.Pod) {
		var ret string
		return ret
	}
	return *o.Pod
}

// GetPodOk returns a tuple with the Pod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientKubernetesAlertInfo) GetPodOk() (*string, bool) {
	if o == nil || IsNil(o.Pod) {
		return nil, false
	}
	return o.Pod, true
}

// HasPod returns a boolean if a field has been set.
func (o *ClientKubernetesAlertInfo) HasPod() bool {
	if o != nil && !IsNil(o.Pod) {
		return true
	}

	return false
}

// SetPod gets a reference to the given string and assigns it to the Pod field.
func (o *ClientKubernetesAlertInfo) SetPod(v string) {
	o.Pod = &v
}

// GetPodLabels returns the PodLabels field value if set, zero value otherwise.
func (o *ClientKubernetesAlertInfo) GetPodLabels() string {
	if o == nil || IsNil(o.PodLabels) {
		var ret string
		return ret
	}
	return *o.PodLabels
}

// GetPodLabelsOk returns a tuple with the PodLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientKubernetesAlertInfo) GetPodLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.PodLabels) {
		return nil, false
	}
	return o.PodLabels, true
}

// HasPodLabels returns a boolean if a field has been set.
func (o *ClientKubernetesAlertInfo) HasPodLabels() bool {
	if o != nil && !IsNil(o.PodLabels) {
		return true
	}

	return false
}

// SetPodLabels gets a reference to the given string and assigns it to the PodLabels field.
func (o *ClientKubernetesAlertInfo) SetPodLabels(v string) {
	o.PodLabels = &v
}

func (o ClientKubernetesAlertInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientKubernetesAlertInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cluster) {
		toSerialize["cluster"] = o.Cluster
	}
	if !IsNil(o.ControllerKind) {
		toSerialize["controllerKind"] = o.ControllerKind
	}
	if !IsNil(o.ControllerLabels) {
		toSerialize["controllerLabels"] = o.ControllerLabels
	}
	if !IsNil(o.ControllerName) {
		toSerialize["controllerName"] = o.ControllerName
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.NamespaceLabels) {
		toSerialize["namespaceLabels"] = o.NamespaceLabels
	}
	if !IsNil(o.Node) {
		toSerialize["node"] = o.Node
	}
	if !IsNil(o.Pod) {
		toSerialize["pod"] = o.Pod
	}
	if !IsNil(o.PodLabels) {
		toSerialize["podLabels"] = o.PodLabels
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClientKubernetesAlertInfo) UnmarshalJSON(data []byte) (err error) {
	varClientKubernetesAlertInfo := _ClientKubernetesAlertInfo{}

	err = json.Unmarshal(data, &varClientKubernetesAlertInfo)

	if err != nil {
		return err
	}

	*o = ClientKubernetesAlertInfo(varClientKubernetesAlertInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cluster")
		delete(additionalProperties, "controllerKind")
		delete(additionalProperties, "controllerLabels")
		delete(additionalProperties, "controllerName")
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "namespaceLabels")
		delete(additionalProperties, "node")
		delete(additionalProperties, "pod")
		delete(additionalProperties, "podLabels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClientKubernetesAlertInfo struct {
	value *ClientKubernetesAlertInfo
	isSet bool
}

func (v NullableClientKubernetesAlertInfo) Get() *ClientKubernetesAlertInfo {
	return v.value
}

func (v *NullableClientKubernetesAlertInfo) Set(val *ClientKubernetesAlertInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableClientKubernetesAlertInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableClientKubernetesAlertInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientKubernetesAlertInfo(val *ClientKubernetesAlertInfo) *NullableClientKubernetesAlertInfo {
	return &NullableClientKubernetesAlertInfo{value: val, isSet: true}
}

func (v NullableClientKubernetesAlertInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientKubernetesAlertInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
