/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the ScriptsServiceScript type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScriptsServiceScript{}

// ScriptsServiceScript struct for ScriptsServiceScript
type ScriptsServiceScript struct {
	Description          *string `json:"description,omitempty"`
	Id                   *string `json:"id,omitempty"`
	Name                 *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ScriptsServiceScript ScriptsServiceScript

// NewScriptsServiceScript instantiates a new ScriptsServiceScript object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptsServiceScript() *ScriptsServiceScript {
	this := ScriptsServiceScript{}
	return &this
}

// NewScriptsServiceScriptWithDefaults instantiates a new ScriptsServiceScript object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptsServiceScriptWithDefaults() *ScriptsServiceScript {
	this := ScriptsServiceScript{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ScriptsServiceScript) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsServiceScript) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ScriptsServiceScript) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ScriptsServiceScript) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ScriptsServiceScript) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsServiceScript) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ScriptsServiceScript) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ScriptsServiceScript) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ScriptsServiceScript) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScriptsServiceScript) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ScriptsServiceScript) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ScriptsServiceScript) SetName(v string) {
	o.Name = &v
}

func (o ScriptsServiceScript) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScriptsServiceScript) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScriptsServiceScript) UnmarshalJSON(data []byte) (err error) {
	varScriptsServiceScript := _ScriptsServiceScript{}

	err = json.Unmarshal(data, &varScriptsServiceScript)

	if err != nil {
		return err
	}

	*o = ScriptsServiceScript(varScriptsServiceScript)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScriptsServiceScript struct {
	value *ScriptsServiceScript
	isSet bool
}

func (v NullableScriptsServiceScript) Get() *ScriptsServiceScript {
	return v.value
}

func (v *NullableScriptsServiceScript) Set(val *ScriptsServiceScript) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptsServiceScript) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptsServiceScript) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptsServiceScript(val *ScriptsServiceScript) *NullableScriptsServiceScript {
	return &NullableScriptsServiceScript{value: val, isSet: true}
}

func (v NullableScriptsServiceScript) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptsServiceScript) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
