/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
	"fmt"
)

// checks if the InstalledAppsInstalledAppsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstalledAppsInstalledAppsRequest{}

// InstalledAppsInstalledAppsRequest struct for InstalledAppsInstalledAppsRequest
type InstalledAppsInstalledAppsRequest struct {
	AgentIds             []string `json:"agent_ids"`
	Limit                int32    `json:"limit"`
	Skip                 int32    `json:"skip"`
	SortDirection        string   `json:"sort_direction"`
	SortField            string   `json:"sort_field"`
	AdditionalProperties map[string]interface{}
}

type _InstalledAppsInstalledAppsRequest InstalledAppsInstalledAppsRequest

// NewInstalledAppsInstalledAppsRequest instantiates a new InstalledAppsInstalledAppsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstalledAppsInstalledAppsRequest(agentIds []string, limit int32, skip int32, sortDirection string, sortField string) *InstalledAppsInstalledAppsRequest {
	this := InstalledAppsInstalledAppsRequest{}
	this.AgentIds = agentIds
	this.Limit = limit
	this.Skip = skip
	this.SortDirection = sortDirection
	this.SortField = sortField
	return &this
}

// NewInstalledAppsInstalledAppsRequestWithDefaults instantiates a new InstalledAppsInstalledAppsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstalledAppsInstalledAppsRequestWithDefaults() *InstalledAppsInstalledAppsRequest {
	this := InstalledAppsInstalledAppsRequest{}
	return &this
}

// GetAgentIds returns the AgentIds field value
func (o *InstalledAppsInstalledAppsRequest) GetAgentIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AgentIds
}

// GetAgentIdsOk returns a tuple with the AgentIds field value
// and a boolean to check if the value has been set.
func (o *InstalledAppsInstalledAppsRequest) GetAgentIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentIds, true
}

// SetAgentIds sets field value
func (o *InstalledAppsInstalledAppsRequest) SetAgentIds(v []string) {
	o.AgentIds = v
}

// GetLimit returns the Limit field value
func (o *InstalledAppsInstalledAppsRequest) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *InstalledAppsInstalledAppsRequest) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *InstalledAppsInstalledAppsRequest) SetLimit(v int32) {
	o.Limit = v
}

// GetSkip returns the Skip field value
func (o *InstalledAppsInstalledAppsRequest) GetSkip() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Skip
}

// GetSkipOk returns a tuple with the Skip field value
// and a boolean to check if the value has been set.
func (o *InstalledAppsInstalledAppsRequest) GetSkipOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Skip, true
}

// SetSkip sets field value
func (o *InstalledAppsInstalledAppsRequest) SetSkip(v int32) {
	o.Skip = v
}

// GetSortDirection returns the SortDirection field value
func (o *InstalledAppsInstalledAppsRequest) GetSortDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SortDirection
}

// GetSortDirectionOk returns a tuple with the SortDirection field value
// and a boolean to check if the value has been set.
func (o *InstalledAppsInstalledAppsRequest) GetSortDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SortDirection, true
}

// SetSortDirection sets field value
func (o *InstalledAppsInstalledAppsRequest) SetSortDirection(v string) {
	o.SortDirection = v
}

// GetSortField returns the SortField field value
func (o *InstalledAppsInstalledAppsRequest) GetSortField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SortField
}

// GetSortFieldOk returns a tuple with the SortField field value
// and a boolean to check if the value has been set.
func (o *InstalledAppsInstalledAppsRequest) GetSortFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SortField, true
}

// SetSortField sets field value
func (o *InstalledAppsInstalledAppsRequest) SetSortField(v string) {
	o.SortField = v
}

func (o InstalledAppsInstalledAppsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstalledAppsInstalledAppsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_ids"] = o.AgentIds
	toSerialize["limit"] = o.Limit
	toSerialize["skip"] = o.Skip
	toSerialize["sort_direction"] = o.SortDirection
	toSerialize["sort_field"] = o.SortField

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InstalledAppsInstalledAppsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_ids",
		"limit",
		"skip",
		"sort_direction",
		"sort_field",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInstalledAppsInstalledAppsRequest := _InstalledAppsInstalledAppsRequest{}

	err = json.Unmarshal(data, &varInstalledAppsInstalledAppsRequest)

	if err != nil {
		return err
	}

	*o = InstalledAppsInstalledAppsRequest(varInstalledAppsInstalledAppsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "agent_ids")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "skip")
		delete(additionalProperties, "sort_direction")
		delete(additionalProperties, "sort_field")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInstalledAppsInstalledAppsRequest struct {
	value *InstalledAppsInstalledAppsRequest
	isSet bool
}

func (v NullableInstalledAppsInstalledAppsRequest) Get() *InstalledAppsInstalledAppsRequest {
	return v.value
}

func (v *NullableInstalledAppsInstalledAppsRequest) Set(val *InstalledAppsInstalledAppsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstalledAppsInstalledAppsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstalledAppsInstalledAppsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstalledAppsInstalledAppsRequest(val *InstalledAppsInstalledAppsRequest) *NullableInstalledAppsInstalledAppsRequest {
	return &NullableInstalledAppsInstalledAppsRequest{value: val, isSet: true}
}

func (v NullableInstalledAppsInstalledAppsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstalledAppsInstalledAppsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
