/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the DeviceUsersServiceEndUsersDevicesImportMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceUsersServiceEndUsersDevicesImportMetadata{}

// DeviceUsersServiceEndUsersDevicesImportMetadata struct for DeviceUsersServiceEndUsersDevicesImportMetadata
type DeviceUsersServiceEndUsersDevicesImportMetadata struct {
	Errors               []DeviceUsersServiceRowError `json:"errors,omitempty"`
	FileId               *string                      `json:"file_id,omitempty"`
	Filename             *string                      `json:"filename,omitempty"`
	OrganizationId       *string                      `json:"organization_id,omitempty"`
	ProcessedTimestamp   *string                      `json:"processed_timestamp,omitempty"`
	RequestedTimestamp   *string                      `json:"requested_timestamp,omitempty"`
	RowCount             *int32                       `json:"row_count,omitempty"`
	Status               *string                      `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeviceUsersServiceEndUsersDevicesImportMetadata DeviceUsersServiceEndUsersDevicesImportMetadata

// NewDeviceUsersServiceEndUsersDevicesImportMetadata instantiates a new DeviceUsersServiceEndUsersDevicesImportMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceUsersServiceEndUsersDevicesImportMetadata() *DeviceUsersServiceEndUsersDevicesImportMetadata {
	this := DeviceUsersServiceEndUsersDevicesImportMetadata{}
	return &this
}

// NewDeviceUsersServiceEndUsersDevicesImportMetadataWithDefaults instantiates a new DeviceUsersServiceEndUsersDevicesImportMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceUsersServiceEndUsersDevicesImportMetadataWithDefaults() *DeviceUsersServiceEndUsersDevicesImportMetadata {
	this := DeviceUsersServiceEndUsersDevicesImportMetadata{}
	return &this
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetErrors() []DeviceUsersServiceRowError {
	if o == nil || IsNil(o.Errors) {
		var ret []DeviceUsersServiceRowError
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetErrorsOk() ([]DeviceUsersServiceRowError, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []DeviceUsersServiceRowError and assigns it to the Errors field.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) SetErrors(v []DeviceUsersServiceRowError) {
	o.Errors = v
}

// GetFileId returns the FileId field value if set, zero value otherwise.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetFileId() string {
	if o == nil || IsNil(o.FileId) {
		var ret string
		return ret
	}
	return *o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetFileIdOk() (*string, bool) {
	if o == nil || IsNil(o.FileId) {
		return nil, false
	}
	return o.FileId, true
}

// HasFileId returns a boolean if a field has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) HasFileId() bool {
	if o != nil && !IsNil(o.FileId) {
		return true
	}

	return false
}

// SetFileId gets a reference to the given string and assigns it to the FileId field.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) SetFileId(v string) {
	o.FileId = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) SetFilename(v string) {
	o.Filename = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetProcessedTimestamp returns the ProcessedTimestamp field value if set, zero value otherwise.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetProcessedTimestamp() string {
	if o == nil || IsNil(o.ProcessedTimestamp) {
		var ret string
		return ret
	}
	return *o.ProcessedTimestamp
}

// GetProcessedTimestampOk returns a tuple with the ProcessedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetProcessedTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.ProcessedTimestamp) {
		return nil, false
	}
	return o.ProcessedTimestamp, true
}

// HasProcessedTimestamp returns a boolean if a field has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) HasProcessedTimestamp() bool {
	if o != nil && !IsNil(o.ProcessedTimestamp) {
		return true
	}

	return false
}

// SetProcessedTimestamp gets a reference to the given string and assigns it to the ProcessedTimestamp field.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) SetProcessedTimestamp(v string) {
	o.ProcessedTimestamp = &v
}

// GetRequestedTimestamp returns the RequestedTimestamp field value if set, zero value otherwise.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetRequestedTimestamp() string {
	if o == nil || IsNil(o.RequestedTimestamp) {
		var ret string
		return ret
	}
	return *o.RequestedTimestamp
}

// GetRequestedTimestampOk returns a tuple with the RequestedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetRequestedTimestampOk() (*string, bool) {
	if o == nil || IsNil(o.RequestedTimestamp) {
		return nil, false
	}
	return o.RequestedTimestamp, true
}

// HasRequestedTimestamp returns a boolean if a field has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) HasRequestedTimestamp() bool {
	if o != nil && !IsNil(o.RequestedTimestamp) {
		return true
	}

	return false
}

// SetRequestedTimestamp gets a reference to the given string and assigns it to the RequestedTimestamp field.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) SetRequestedTimestamp(v string) {
	o.RequestedTimestamp = &v
}

// GetRowCount returns the RowCount field value if set, zero value otherwise.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetRowCount() int32 {
	if o == nil || IsNil(o.RowCount) {
		var ret int32
		return ret
	}
	return *o.RowCount
}

// GetRowCountOk returns a tuple with the RowCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetRowCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RowCount) {
		return nil, false
	}
	return o.RowCount, true
}

// HasRowCount returns a boolean if a field has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) HasRowCount() bool {
	if o != nil && !IsNil(o.RowCount) {
		return true
	}

	return false
}

// SetRowCount gets a reference to the given int32 and assigns it to the RowCount field.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) SetRowCount(v int32) {
	o.RowCount = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) SetStatus(v string) {
	o.Status = &v
}

func (o DeviceUsersServiceEndUsersDevicesImportMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceUsersServiceEndUsersDevicesImportMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.FileId) {
		toSerialize["file_id"] = o.FileId
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !IsNil(o.ProcessedTimestamp) {
		toSerialize["processed_timestamp"] = o.ProcessedTimestamp
	}
	if !IsNil(o.RequestedTimestamp) {
		toSerialize["requested_timestamp"] = o.RequestedTimestamp
	}
	if !IsNil(o.RowCount) {
		toSerialize["row_count"] = o.RowCount
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeviceUsersServiceEndUsersDevicesImportMetadata) UnmarshalJSON(data []byte) (err error) {
	varDeviceUsersServiceEndUsersDevicesImportMetadata := _DeviceUsersServiceEndUsersDevicesImportMetadata{}

	err = json.Unmarshal(data, &varDeviceUsersServiceEndUsersDevicesImportMetadata)

	if err != nil {
		return err
	}

	*o = DeviceUsersServiceEndUsersDevicesImportMetadata(varDeviceUsersServiceEndUsersDevicesImportMetadata)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "errors")
		delete(additionalProperties, "file_id")
		delete(additionalProperties, "filename")
		delete(additionalProperties, "organization_id")
		delete(additionalProperties, "processed_timestamp")
		delete(additionalProperties, "requested_timestamp")
		delete(additionalProperties, "row_count")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeviceUsersServiceEndUsersDevicesImportMetadata struct {
	value *DeviceUsersServiceEndUsersDevicesImportMetadata
	isSet bool
}

func (v NullableDeviceUsersServiceEndUsersDevicesImportMetadata) Get() *DeviceUsersServiceEndUsersDevicesImportMetadata {
	return v.value
}

func (v *NullableDeviceUsersServiceEndUsersDevicesImportMetadata) Set(val *DeviceUsersServiceEndUsersDevicesImportMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceUsersServiceEndUsersDevicesImportMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceUsersServiceEndUsersDevicesImportMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceUsersServiceEndUsersDevicesImportMetadata(val *DeviceUsersServiceEndUsersDevicesImportMetadata) *NullableDeviceUsersServiceEndUsersDevicesImportMetadata {
	return &NullableDeviceUsersServiceEndUsersDevicesImportMetadata{value: val, isSet: true}
}

func (v NullableDeviceUsersServiceEndUsersDevicesImportMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceUsersServiceEndUsersDevicesImportMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
