/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the ClientGetAlertsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientGetAlertsData{}

// ClientGetAlertsData struct for ClientGetAlertsData
type ClientGetAlertsData struct {
	AgentDetectionInfo      *ClientAgentAlertDetectionInfo `json:"agentDetectionInfo,omitempty"`
	AlertInfo               *ClientAlertInfo               `json:"alertInfo,omitempty"`
	ContainerInfo           *ClientContainerAlertInfo      `json:"containerInfo,omitempty"`
	KubernetesInfo          *ClientKubernetesAlertInfo     `json:"kubernetesInfo,omitempty"`
	RuleInfo                *ClientRuleInfo                `json:"ruleInfo,omitempty"`
	SourceParentProcessInfo *ClientSourceParentProcessInfo `json:"sourceParentProcessInfo,omitempty"`
	SourceProcessInfo       *ClientSourceProcessInfo       `json:"sourceProcessInfo,omitempty"`
	TargetProcessInfo       *ClientTargetProcessInfo       `json:"targetProcessInfo,omitempty"`
	AdditionalProperties    map[string]interface{}
}

type _ClientGetAlertsData ClientGetAlertsData

// NewClientGetAlertsData instantiates a new ClientGetAlertsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientGetAlertsData() *ClientGetAlertsData {
	this := ClientGetAlertsData{}
	return &this
}

// NewClientGetAlertsDataWithDefaults instantiates a new ClientGetAlertsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientGetAlertsDataWithDefaults() *ClientGetAlertsData {
	this := ClientGetAlertsData{}
	return &this
}

// GetAgentDetectionInfo returns the AgentDetectionInfo field value if set, zero value otherwise.
func (o *ClientGetAlertsData) GetAgentDetectionInfo() ClientAgentAlertDetectionInfo {
	if o == nil || IsNil(o.AgentDetectionInfo) {
		var ret ClientAgentAlertDetectionInfo
		return ret
	}
	return *o.AgentDetectionInfo
}

// GetAgentDetectionInfoOk returns a tuple with the AgentDetectionInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientGetAlertsData) GetAgentDetectionInfoOk() (*ClientAgentAlertDetectionInfo, bool) {
	if o == nil || IsNil(o.AgentDetectionInfo) {
		return nil, false
	}
	return o.AgentDetectionInfo, true
}

// HasAgentDetectionInfo returns a boolean if a field has been set.
func (o *ClientGetAlertsData) HasAgentDetectionInfo() bool {
	if o != nil && !IsNil(o.AgentDetectionInfo) {
		return true
	}

	return false
}

// SetAgentDetectionInfo gets a reference to the given ClientAgentAlertDetectionInfo and assigns it to the AgentDetectionInfo field.
func (o *ClientGetAlertsData) SetAgentDetectionInfo(v ClientAgentAlertDetectionInfo) {
	o.AgentDetectionInfo = &v
}

// GetAlertInfo returns the AlertInfo field value if set, zero value otherwise.
func (o *ClientGetAlertsData) GetAlertInfo() ClientAlertInfo {
	if o == nil || IsNil(o.AlertInfo) {
		var ret ClientAlertInfo
		return ret
	}
	return *o.AlertInfo
}

// GetAlertInfoOk returns a tuple with the AlertInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientGetAlertsData) GetAlertInfoOk() (*ClientAlertInfo, bool) {
	if o == nil || IsNil(o.AlertInfo) {
		return nil, false
	}
	return o.AlertInfo, true
}

// HasAlertInfo returns a boolean if a field has been set.
func (o *ClientGetAlertsData) HasAlertInfo() bool {
	if o != nil && !IsNil(o.AlertInfo) {
		return true
	}

	return false
}

// SetAlertInfo gets a reference to the given ClientAlertInfo and assigns it to the AlertInfo field.
func (o *ClientGetAlertsData) SetAlertInfo(v ClientAlertInfo) {
	o.AlertInfo = &v
}

// GetContainerInfo returns the ContainerInfo field value if set, zero value otherwise.
func (o *ClientGetAlertsData) GetContainerInfo() ClientContainerAlertInfo {
	if o == nil || IsNil(o.ContainerInfo) {
		var ret ClientContainerAlertInfo
		return ret
	}
	return *o.ContainerInfo
}

// GetContainerInfoOk returns a tuple with the ContainerInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientGetAlertsData) GetContainerInfoOk() (*ClientContainerAlertInfo, bool) {
	if o == nil || IsNil(o.ContainerInfo) {
		return nil, false
	}
	return o.ContainerInfo, true
}

// HasContainerInfo returns a boolean if a field has been set.
func (o *ClientGetAlertsData) HasContainerInfo() bool {
	if o != nil && !IsNil(o.ContainerInfo) {
		return true
	}

	return false
}

// SetContainerInfo gets a reference to the given ClientContainerAlertInfo and assigns it to the ContainerInfo field.
func (o *ClientGetAlertsData) SetContainerInfo(v ClientContainerAlertInfo) {
	o.ContainerInfo = &v
}

// GetKubernetesInfo returns the KubernetesInfo field value if set, zero value otherwise.
func (o *ClientGetAlertsData) GetKubernetesInfo() ClientKubernetesAlertInfo {
	if o == nil || IsNil(o.KubernetesInfo) {
		var ret ClientKubernetesAlertInfo
		return ret
	}
	return *o.KubernetesInfo
}

// GetKubernetesInfoOk returns a tuple with the KubernetesInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientGetAlertsData) GetKubernetesInfoOk() (*ClientKubernetesAlertInfo, bool) {
	if o == nil || IsNil(o.KubernetesInfo) {
		return nil, false
	}
	return o.KubernetesInfo, true
}

// HasKubernetesInfo returns a boolean if a field has been set.
func (o *ClientGetAlertsData) HasKubernetesInfo() bool {
	if o != nil && !IsNil(o.KubernetesInfo) {
		return true
	}

	return false
}

// SetKubernetesInfo gets a reference to the given ClientKubernetesAlertInfo and assigns it to the KubernetesInfo field.
func (o *ClientGetAlertsData) SetKubernetesInfo(v ClientKubernetesAlertInfo) {
	o.KubernetesInfo = &v
}

// GetRuleInfo returns the RuleInfo field value if set, zero value otherwise.
func (o *ClientGetAlertsData) GetRuleInfo() ClientRuleInfo {
	if o == nil || IsNil(o.RuleInfo) {
		var ret ClientRuleInfo
		return ret
	}
	return *o.RuleInfo
}

// GetRuleInfoOk returns a tuple with the RuleInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientGetAlertsData) GetRuleInfoOk() (*ClientRuleInfo, bool) {
	if o == nil || IsNil(o.RuleInfo) {
		return nil, false
	}
	return o.RuleInfo, true
}

// HasRuleInfo returns a boolean if a field has been set.
func (o *ClientGetAlertsData) HasRuleInfo() bool {
	if o != nil && !IsNil(o.RuleInfo) {
		return true
	}

	return false
}

// SetRuleInfo gets a reference to the given ClientRuleInfo and assigns it to the RuleInfo field.
func (o *ClientGetAlertsData) SetRuleInfo(v ClientRuleInfo) {
	o.RuleInfo = &v
}

// GetSourceParentProcessInfo returns the SourceParentProcessInfo field value if set, zero value otherwise.
func (o *ClientGetAlertsData) GetSourceParentProcessInfo() ClientSourceParentProcessInfo {
	if o == nil || IsNil(o.SourceParentProcessInfo) {
		var ret ClientSourceParentProcessInfo
		return ret
	}
	return *o.SourceParentProcessInfo
}

// GetSourceParentProcessInfoOk returns a tuple with the SourceParentProcessInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientGetAlertsData) GetSourceParentProcessInfoOk() (*ClientSourceParentProcessInfo, bool) {
	if o == nil || IsNil(o.SourceParentProcessInfo) {
		return nil, false
	}
	return o.SourceParentProcessInfo, true
}

// HasSourceParentProcessInfo returns a boolean if a field has been set.
func (o *ClientGetAlertsData) HasSourceParentProcessInfo() bool {
	if o != nil && !IsNil(o.SourceParentProcessInfo) {
		return true
	}

	return false
}

// SetSourceParentProcessInfo gets a reference to the given ClientSourceParentProcessInfo and assigns it to the SourceParentProcessInfo field.
func (o *ClientGetAlertsData) SetSourceParentProcessInfo(v ClientSourceParentProcessInfo) {
	o.SourceParentProcessInfo = &v
}

// GetSourceProcessInfo returns the SourceProcessInfo field value if set, zero value otherwise.
func (o *ClientGetAlertsData) GetSourceProcessInfo() ClientSourceProcessInfo {
	if o == nil || IsNil(o.SourceProcessInfo) {
		var ret ClientSourceProcessInfo
		return ret
	}
	return *o.SourceProcessInfo
}

// GetSourceProcessInfoOk returns a tuple with the SourceProcessInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientGetAlertsData) GetSourceProcessInfoOk() (*ClientSourceProcessInfo, bool) {
	if o == nil || IsNil(o.SourceProcessInfo) {
		return nil, false
	}
	return o.SourceProcessInfo, true
}

// HasSourceProcessInfo returns a boolean if a field has been set.
func (o *ClientGetAlertsData) HasSourceProcessInfo() bool {
	if o != nil && !IsNil(o.SourceProcessInfo) {
		return true
	}

	return false
}

// SetSourceProcessInfo gets a reference to the given ClientSourceProcessInfo and assigns it to the SourceProcessInfo field.
func (o *ClientGetAlertsData) SetSourceProcessInfo(v ClientSourceProcessInfo) {
	o.SourceProcessInfo = &v
}

// GetTargetProcessInfo returns the TargetProcessInfo field value if set, zero value otherwise.
func (o *ClientGetAlertsData) GetTargetProcessInfo() ClientTargetProcessInfo {
	if o == nil || IsNil(o.TargetProcessInfo) {
		var ret ClientTargetProcessInfo
		return ret
	}
	return *o.TargetProcessInfo
}

// GetTargetProcessInfoOk returns a tuple with the TargetProcessInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientGetAlertsData) GetTargetProcessInfoOk() (*ClientTargetProcessInfo, bool) {
	if o == nil || IsNil(o.TargetProcessInfo) {
		return nil, false
	}
	return o.TargetProcessInfo, true
}

// HasTargetProcessInfo returns a boolean if a field has been set.
func (o *ClientGetAlertsData) HasTargetProcessInfo() bool {
	if o != nil && !IsNil(o.TargetProcessInfo) {
		return true
	}

	return false
}

// SetTargetProcessInfo gets a reference to the given ClientTargetProcessInfo and assigns it to the TargetProcessInfo field.
func (o *ClientGetAlertsData) SetTargetProcessInfo(v ClientTargetProcessInfo) {
	o.TargetProcessInfo = &v
}

func (o ClientGetAlertsData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientGetAlertsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentDetectionInfo) {
		toSerialize["agentDetectionInfo"] = o.AgentDetectionInfo
	}
	if !IsNil(o.AlertInfo) {
		toSerialize["alertInfo"] = o.AlertInfo
	}
	if !IsNil(o.ContainerInfo) {
		toSerialize["containerInfo"] = o.ContainerInfo
	}
	if !IsNil(o.KubernetesInfo) {
		toSerialize["kubernetesInfo"] = o.KubernetesInfo
	}
	if !IsNil(o.RuleInfo) {
		toSerialize["ruleInfo"] = o.RuleInfo
	}
	if !IsNil(o.SourceParentProcessInfo) {
		toSerialize["sourceParentProcessInfo"] = o.SourceParentProcessInfo
	}
	if !IsNil(o.SourceProcessInfo) {
		toSerialize["sourceProcessInfo"] = o.SourceProcessInfo
	}
	if !IsNil(o.TargetProcessInfo) {
		toSerialize["targetProcessInfo"] = o.TargetProcessInfo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClientGetAlertsData) UnmarshalJSON(data []byte) (err error) {
	varClientGetAlertsData := _ClientGetAlertsData{}

	err = json.Unmarshal(data, &varClientGetAlertsData)

	if err != nil {
		return err
	}

	*o = ClientGetAlertsData(varClientGetAlertsData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "agentDetectionInfo")
		delete(additionalProperties, "alertInfo")
		delete(additionalProperties, "containerInfo")
		delete(additionalProperties, "kubernetesInfo")
		delete(additionalProperties, "ruleInfo")
		delete(additionalProperties, "sourceParentProcessInfo")
		delete(additionalProperties, "sourceProcessInfo")
		delete(additionalProperties, "targetProcessInfo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClientGetAlertsData struct {
	value *ClientGetAlertsData
	isSet bool
}

func (v NullableClientGetAlertsData) Get() *ClientGetAlertsData {
	return v.value
}

func (v *NullableClientGetAlertsData) Set(val *ClientGetAlertsData) {
	v.value = val
	v.isSet = true
}

func (v NullableClientGetAlertsData) IsSet() bool {
	return v.isSet
}

func (v *NullableClientGetAlertsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientGetAlertsData(val *ClientGetAlertsData) *NullableClientGetAlertsData {
	return &NullableClientGetAlertsData{value: val, isSet: true}
}

func (v NullableClientGetAlertsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientGetAlertsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
