/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the FileTrackEntitiesFilesTrackedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileTrackEntitiesFilesTrackedRequest{}

// FileTrackEntitiesFilesTrackedRequest struct for FileTrackEntitiesFilesTrackedRequest
type FileTrackEntitiesFilesTrackedRequest struct {
	FileIds              []string `json:"file_ids,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FileTrackEntitiesFilesTrackedRequest FileTrackEntitiesFilesTrackedRequest

// NewFileTrackEntitiesFilesTrackedRequest instantiates a new FileTrackEntitiesFilesTrackedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileTrackEntitiesFilesTrackedRequest() *FileTrackEntitiesFilesTrackedRequest {
	this := FileTrackEntitiesFilesTrackedRequest{}
	return &this
}

// NewFileTrackEntitiesFilesTrackedRequestWithDefaults instantiates a new FileTrackEntitiesFilesTrackedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileTrackEntitiesFilesTrackedRequestWithDefaults() *FileTrackEntitiesFilesTrackedRequest {
	this := FileTrackEntitiesFilesTrackedRequest{}
	return &this
}

// GetFileIds returns the FileIds field value if set, zero value otherwise.
func (o *FileTrackEntitiesFilesTrackedRequest) GetFileIds() []string {
	if o == nil || IsNil(o.FileIds) {
		var ret []string
		return ret
	}
	return o.FileIds
}

// GetFileIdsOk returns a tuple with the FileIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileTrackEntitiesFilesTrackedRequest) GetFileIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.FileIds) {
		return nil, false
	}
	return o.FileIds, true
}

// HasFileIds returns a boolean if a field has been set.
func (o *FileTrackEntitiesFilesTrackedRequest) HasFileIds() bool {
	if o != nil && !IsNil(o.FileIds) {
		return true
	}

	return false
}

// SetFileIds gets a reference to the given []string and assigns it to the FileIds field.
func (o *FileTrackEntitiesFilesTrackedRequest) SetFileIds(v []string) {
	o.FileIds = v
}

func (o FileTrackEntitiesFilesTrackedRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileTrackEntitiesFilesTrackedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FileIds) {
		toSerialize["file_ids"] = o.FileIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FileTrackEntitiesFilesTrackedRequest) UnmarshalJSON(data []byte) (err error) {
	varFileTrackEntitiesFilesTrackedRequest := _FileTrackEntitiesFilesTrackedRequest{}

	err = json.Unmarshal(data, &varFileTrackEntitiesFilesTrackedRequest)

	if err != nil {
		return err
	}

	*o = FileTrackEntitiesFilesTrackedRequest(varFileTrackEntitiesFilesTrackedRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "file_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFileTrackEntitiesFilesTrackedRequest struct {
	value *FileTrackEntitiesFilesTrackedRequest
	isSet bool
}

func (v NullableFileTrackEntitiesFilesTrackedRequest) Get() *FileTrackEntitiesFilesTrackedRequest {
	return v.value
}

func (v *NullableFileTrackEntitiesFilesTrackedRequest) Set(val *FileTrackEntitiesFilesTrackedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFileTrackEntitiesFilesTrackedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFileTrackEntitiesFilesTrackedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileTrackEntitiesFilesTrackedRequest(val *FileTrackEntitiesFilesTrackedRequest) *NullableFileTrackEntitiesFilesTrackedRequest {
	return &NullableFileTrackEntitiesFilesTrackedRequest{value: val, isSet: true}
}

func (v NullableFileTrackEntitiesFilesTrackedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileTrackEntitiesFilesTrackedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
