/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the CommunityCommunityScript type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityCommunityScript{}

// CommunityCommunityScript struct for CommunityCommunityScript
type CommunityCommunityScript struct {
	Id                      *string                     `json:"_id,omitempty"`
	AvgRating               *int32                      `json:"avg_rating,omitempty"`
	Categories              []string                    `json:"categories,omitempty"`
	Commandid               *string                     `json:"commandid,omitempty"`
	Comments                []CommunityCommunityComment `json:"comments,omitempty"`
	CommunityItemIdentifier *string                     `json:"community_item_identifier,omitempty"`
	CommunityVersion        *int32                      `json:"community_version,omitempty"`
	CompanyName             *string                     `json:"company_name,omitempty"`
	Description             *string                     `json:"description,omitempty"`
	IAmOwner                *bool                       `json:"i_am_owner,omitempty"`
	ItemType                *string                     `json:"item_type,omitempty"`
	Name                    *string                     `json:"name,omitempty"`
	NumberOfCopies          *int32                      `json:"number_of_copies,omitempty"`
	PublishedDate           *string                     `json:"published_date,omitempty"`
	RatingCount             *int32                      `json:"rating_count,omitempty"`
	SubmitterName           *string                     `json:"submitter_name,omitempty"`
	Text                    *string                     `json:"text,omitempty"`
	UpdatedDate             *string                     `json:"updated_date,omitempty"`
	Version                 *int32                      `json:"version,omitempty"`
	AdditionalProperties    map[string]interface{}
}

type _CommunityCommunityScript CommunityCommunityScript

// NewCommunityCommunityScript instantiates a new CommunityCommunityScript object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityCommunityScript() *CommunityCommunityScript {
	this := CommunityCommunityScript{}
	return &this
}

// NewCommunityCommunityScriptWithDefaults instantiates a new CommunityCommunityScript object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityCommunityScriptWithDefaults() *CommunityCommunityScript {
	this := CommunityCommunityScript{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CommunityCommunityScript) SetId(v string) {
	o.Id = &v
}

// GetAvgRating returns the AvgRating field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetAvgRating() int32 {
	if o == nil || IsNil(o.AvgRating) {
		var ret int32
		return ret
	}
	return *o.AvgRating
}

// GetAvgRatingOk returns a tuple with the AvgRating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetAvgRatingOk() (*int32, bool) {
	if o == nil || IsNil(o.AvgRating) {
		return nil, false
	}
	return o.AvgRating, true
}

// HasAvgRating returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasAvgRating() bool {
	if o != nil && !IsNil(o.AvgRating) {
		return true
	}

	return false
}

// SetAvgRating gets a reference to the given int32 and assigns it to the AvgRating field.
func (o *CommunityCommunityScript) SetAvgRating(v int32) {
	o.AvgRating = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetCategories() []string {
	if o == nil || IsNil(o.Categories) {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *CommunityCommunityScript) SetCategories(v []string) {
	o.Categories = v
}

// GetCommandid returns the Commandid field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetCommandid() string {
	if o == nil || IsNil(o.Commandid) {
		var ret string
		return ret
	}
	return *o.Commandid
}

// GetCommandidOk returns a tuple with the Commandid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetCommandidOk() (*string, bool) {
	if o == nil || IsNil(o.Commandid) {
		return nil, false
	}
	return o.Commandid, true
}

// HasCommandid returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasCommandid() bool {
	if o != nil && !IsNil(o.Commandid) {
		return true
	}

	return false
}

// SetCommandid gets a reference to the given string and assigns it to the Commandid field.
func (o *CommunityCommunityScript) SetCommandid(v string) {
	o.Commandid = &v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetComments() []CommunityCommunityComment {
	if o == nil || IsNil(o.Comments) {
		var ret []CommunityCommunityComment
		return ret
	}
	return o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetCommentsOk() ([]CommunityCommunityComment, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given []CommunityCommunityComment and assigns it to the Comments field.
func (o *CommunityCommunityScript) SetComments(v []CommunityCommunityComment) {
	o.Comments = v
}

// GetCommunityItemIdentifier returns the CommunityItemIdentifier field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetCommunityItemIdentifier() string {
	if o == nil || IsNil(o.CommunityItemIdentifier) {
		var ret string
		return ret
	}
	return *o.CommunityItemIdentifier
}

// GetCommunityItemIdentifierOk returns a tuple with the CommunityItemIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetCommunityItemIdentifierOk() (*string, bool) {
	if o == nil || IsNil(o.CommunityItemIdentifier) {
		return nil, false
	}
	return o.CommunityItemIdentifier, true
}

// HasCommunityItemIdentifier returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasCommunityItemIdentifier() bool {
	if o != nil && !IsNil(o.CommunityItemIdentifier) {
		return true
	}

	return false
}

// SetCommunityItemIdentifier gets a reference to the given string and assigns it to the CommunityItemIdentifier field.
func (o *CommunityCommunityScript) SetCommunityItemIdentifier(v string) {
	o.CommunityItemIdentifier = &v
}

// GetCommunityVersion returns the CommunityVersion field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetCommunityVersion() int32 {
	if o == nil || IsNil(o.CommunityVersion) {
		var ret int32
		return ret
	}
	return *o.CommunityVersion
}

// GetCommunityVersionOk returns a tuple with the CommunityVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetCommunityVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.CommunityVersion) {
		return nil, false
	}
	return o.CommunityVersion, true
}

// HasCommunityVersion returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasCommunityVersion() bool {
	if o != nil && !IsNil(o.CommunityVersion) {
		return true
	}

	return false
}

// SetCommunityVersion gets a reference to the given int32 and assigns it to the CommunityVersion field.
func (o *CommunityCommunityScript) SetCommunityVersion(v int32) {
	o.CommunityVersion = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *CommunityCommunityScript) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CommunityCommunityScript) SetDescription(v string) {
	o.Description = &v
}

// GetIAmOwner returns the IAmOwner field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetIAmOwner() bool {
	if o == nil || IsNil(o.IAmOwner) {
		var ret bool
		return ret
	}
	return *o.IAmOwner
}

// GetIAmOwnerOk returns a tuple with the IAmOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetIAmOwnerOk() (*bool, bool) {
	if o == nil || IsNil(o.IAmOwner) {
		return nil, false
	}
	return o.IAmOwner, true
}

// HasIAmOwner returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasIAmOwner() bool {
	if o != nil && !IsNil(o.IAmOwner) {
		return true
	}

	return false
}

// SetIAmOwner gets a reference to the given bool and assigns it to the IAmOwner field.
func (o *CommunityCommunityScript) SetIAmOwner(v bool) {
	o.IAmOwner = &v
}

// GetItemType returns the ItemType field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetItemType() string {
	if o == nil || IsNil(o.ItemType) {
		var ret string
		return ret
	}
	return *o.ItemType
}

// GetItemTypeOk returns a tuple with the ItemType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetItemTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ItemType) {
		return nil, false
	}
	return o.ItemType, true
}

// HasItemType returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasItemType() bool {
	if o != nil && !IsNil(o.ItemType) {
		return true
	}

	return false
}

// SetItemType gets a reference to the given string and assigns it to the ItemType field.
func (o *CommunityCommunityScript) SetItemType(v string) {
	o.ItemType = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CommunityCommunityScript) SetName(v string) {
	o.Name = &v
}

// GetNumberOfCopies returns the NumberOfCopies field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetNumberOfCopies() int32 {
	if o == nil || IsNil(o.NumberOfCopies) {
		var ret int32
		return ret
	}
	return *o.NumberOfCopies
}

// GetNumberOfCopiesOk returns a tuple with the NumberOfCopies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetNumberOfCopiesOk() (*int32, bool) {
	if o == nil || IsNil(o.NumberOfCopies) {
		return nil, false
	}
	return o.NumberOfCopies, true
}

// HasNumberOfCopies returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasNumberOfCopies() bool {
	if o != nil && !IsNil(o.NumberOfCopies) {
		return true
	}

	return false
}

// SetNumberOfCopies gets a reference to the given int32 and assigns it to the NumberOfCopies field.
func (o *CommunityCommunityScript) SetNumberOfCopies(v int32) {
	o.NumberOfCopies = &v
}

// GetPublishedDate returns the PublishedDate field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetPublishedDate() string {
	if o == nil || IsNil(o.PublishedDate) {
		var ret string
		return ret
	}
	return *o.PublishedDate
}

// GetPublishedDateOk returns a tuple with the PublishedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetPublishedDateOk() (*string, bool) {
	if o == nil || IsNil(o.PublishedDate) {
		return nil, false
	}
	return o.PublishedDate, true
}

// HasPublishedDate returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasPublishedDate() bool {
	if o != nil && !IsNil(o.PublishedDate) {
		return true
	}

	return false
}

// SetPublishedDate gets a reference to the given string and assigns it to the PublishedDate field.
func (o *CommunityCommunityScript) SetPublishedDate(v string) {
	o.PublishedDate = &v
}

// GetRatingCount returns the RatingCount field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetRatingCount() int32 {
	if o == nil || IsNil(o.RatingCount) {
		var ret int32
		return ret
	}
	return *o.RatingCount
}

// GetRatingCountOk returns a tuple with the RatingCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetRatingCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RatingCount) {
		return nil, false
	}
	return o.RatingCount, true
}

// HasRatingCount returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasRatingCount() bool {
	if o != nil && !IsNil(o.RatingCount) {
		return true
	}

	return false
}

// SetRatingCount gets a reference to the given int32 and assigns it to the RatingCount field.
func (o *CommunityCommunityScript) SetRatingCount(v int32) {
	o.RatingCount = &v
}

// GetSubmitterName returns the SubmitterName field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetSubmitterName() string {
	if o == nil || IsNil(o.SubmitterName) {
		var ret string
		return ret
	}
	return *o.SubmitterName
}

// GetSubmitterNameOk returns a tuple with the SubmitterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetSubmitterNameOk() (*string, bool) {
	if o == nil || IsNil(o.SubmitterName) {
		return nil, false
	}
	return o.SubmitterName, true
}

// HasSubmitterName returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasSubmitterName() bool {
	if o != nil && !IsNil(o.SubmitterName) {
		return true
	}

	return false
}

// SetSubmitterName gets a reference to the given string and assigns it to the SubmitterName field.
func (o *CommunityCommunityScript) SetSubmitterName(v string) {
	o.SubmitterName = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *CommunityCommunityScript) SetText(v string) {
	o.Text = &v
}

// GetUpdatedDate returns the UpdatedDate field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetUpdatedDate() string {
	if o == nil || IsNil(o.UpdatedDate) {
		var ret string
		return ret
	}
	return *o.UpdatedDate
}

// GetUpdatedDateOk returns a tuple with the UpdatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetUpdatedDateOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedDate) {
		return nil, false
	}
	return o.UpdatedDate, true
}

// HasUpdatedDate returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasUpdatedDate() bool {
	if o != nil && !IsNil(o.UpdatedDate) {
		return true
	}

	return false
}

// SetUpdatedDate gets a reference to the given string and assigns it to the UpdatedDate field.
func (o *CommunityCommunityScript) SetUpdatedDate(v string) {
	o.UpdatedDate = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CommunityCommunityScript) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityCommunityScript) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CommunityCommunityScript) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *CommunityCommunityScript) SetVersion(v int32) {
	o.Version = &v
}

func (o CommunityCommunityScript) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityCommunityScript) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["_id"] = o.Id
	}
	if !IsNil(o.AvgRating) {
		toSerialize["avg_rating"] = o.AvgRating
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.Commandid) {
		toSerialize["commandid"] = o.Commandid
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if !IsNil(o.CommunityItemIdentifier) {
		toSerialize["community_item_identifier"] = o.CommunityItemIdentifier
	}
	if !IsNil(o.CommunityVersion) {
		toSerialize["community_version"] = o.CommunityVersion
	}
	if !IsNil(o.CompanyName) {
		toSerialize["company_name"] = o.CompanyName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IAmOwner) {
		toSerialize["i_am_owner"] = o.IAmOwner
	}
	if !IsNil(o.ItemType) {
		toSerialize["item_type"] = o.ItemType
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NumberOfCopies) {
		toSerialize["number_of_copies"] = o.NumberOfCopies
	}
	if !IsNil(o.PublishedDate) {
		toSerialize["published_date"] = o.PublishedDate
	}
	if !IsNil(o.RatingCount) {
		toSerialize["rating_count"] = o.RatingCount
	}
	if !IsNil(o.SubmitterName) {
		toSerialize["submitter_name"] = o.SubmitterName
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.UpdatedDate) {
		toSerialize["updated_date"] = o.UpdatedDate
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommunityCommunityScript) UnmarshalJSON(data []byte) (err error) {
	varCommunityCommunityScript := _CommunityCommunityScript{}

	err = json.Unmarshal(data, &varCommunityCommunityScript)

	if err != nil {
		return err
	}

	*o = CommunityCommunityScript(varCommunityCommunityScript)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "_id")
		delete(additionalProperties, "avg_rating")
		delete(additionalProperties, "categories")
		delete(additionalProperties, "commandid")
		delete(additionalProperties, "comments")
		delete(additionalProperties, "community_item_identifier")
		delete(additionalProperties, "community_version")
		delete(additionalProperties, "company_name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "i_am_owner")
		delete(additionalProperties, "item_type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "number_of_copies")
		delete(additionalProperties, "published_date")
		delete(additionalProperties, "rating_count")
		delete(additionalProperties, "submitter_name")
		delete(additionalProperties, "text")
		delete(additionalProperties, "updated_date")
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommunityCommunityScript struct {
	value *CommunityCommunityScript
	isSet bool
}

func (v NullableCommunityCommunityScript) Get() *CommunityCommunityScript {
	return v.value
}

func (v *NullableCommunityCommunityScript) Set(val *CommunityCommunityScript) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityCommunityScript) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityCommunityScript) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityCommunityScript(val *CommunityCommunityScript) *NullableCommunityCommunityScript {
	return &NullableCommunityCommunityScript{value: val, isSet: true}
}

func (v NullableCommunityCommunityScript) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityCommunityScript) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
