/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the DefaultAssetsEntitiesInstructionCommand type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultAssetsEntitiesInstructionCommand{}

// DefaultAssetsEntitiesInstructionCommand struct for DefaultAssetsEntitiesInstructionCommand
type DefaultAssetsEntitiesInstructionCommand struct {
	Instruction          *string `json:"instruction,omitempty"`
	JobName              *string `json:"job_name,omitempty"`
	Type                 *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DefaultAssetsEntitiesInstructionCommand DefaultAssetsEntitiesInstructionCommand

// NewDefaultAssetsEntitiesInstructionCommand instantiates a new DefaultAssetsEntitiesInstructionCommand object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultAssetsEntitiesInstructionCommand() *DefaultAssetsEntitiesInstructionCommand {
	this := DefaultAssetsEntitiesInstructionCommand{}
	return &this
}

// NewDefaultAssetsEntitiesInstructionCommandWithDefaults instantiates a new DefaultAssetsEntitiesInstructionCommand object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultAssetsEntitiesInstructionCommandWithDefaults() *DefaultAssetsEntitiesInstructionCommand {
	this := DefaultAssetsEntitiesInstructionCommand{}
	return &this
}

// GetInstruction returns the Instruction field value if set, zero value otherwise.
func (o *DefaultAssetsEntitiesInstructionCommand) GetInstruction() string {
	if o == nil || IsNil(o.Instruction) {
		var ret string
		return ret
	}
	return *o.Instruction
}

// GetInstructionOk returns a tuple with the Instruction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultAssetsEntitiesInstructionCommand) GetInstructionOk() (*string, bool) {
	if o == nil || IsNil(o.Instruction) {
		return nil, false
	}
	return o.Instruction, true
}

// HasInstruction returns a boolean if a field has been set.
func (o *DefaultAssetsEntitiesInstructionCommand) HasInstruction() bool {
	if o != nil && !IsNil(o.Instruction) {
		return true
	}

	return false
}

// SetInstruction gets a reference to the given string and assigns it to the Instruction field.
func (o *DefaultAssetsEntitiesInstructionCommand) SetInstruction(v string) {
	o.Instruction = &v
}

// GetJobName returns the JobName field value if set, zero value otherwise.
func (o *DefaultAssetsEntitiesInstructionCommand) GetJobName() string {
	if o == nil || IsNil(o.JobName) {
		var ret string
		return ret
	}
	return *o.JobName
}

// GetJobNameOk returns a tuple with the JobName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultAssetsEntitiesInstructionCommand) GetJobNameOk() (*string, bool) {
	if o == nil || IsNil(o.JobName) {
		return nil, false
	}
	return o.JobName, true
}

// HasJobName returns a boolean if a field has been set.
func (o *DefaultAssetsEntitiesInstructionCommand) HasJobName() bool {
	if o != nil && !IsNil(o.JobName) {
		return true
	}

	return false
}

// SetJobName gets a reference to the given string and assigns it to the JobName field.
func (o *DefaultAssetsEntitiesInstructionCommand) SetJobName(v string) {
	o.JobName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *DefaultAssetsEntitiesInstructionCommand) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultAssetsEntitiesInstructionCommand) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *DefaultAssetsEntitiesInstructionCommand) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *DefaultAssetsEntitiesInstructionCommand) SetType(v string) {
	o.Type = &v
}

func (o DefaultAssetsEntitiesInstructionCommand) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultAssetsEntitiesInstructionCommand) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Instruction) {
		toSerialize["instruction"] = o.Instruction
	}
	if !IsNil(o.JobName) {
		toSerialize["job_name"] = o.JobName
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DefaultAssetsEntitiesInstructionCommand) UnmarshalJSON(data []byte) (err error) {
	varDefaultAssetsEntitiesInstructionCommand := _DefaultAssetsEntitiesInstructionCommand{}

	err = json.Unmarshal(data, &varDefaultAssetsEntitiesInstructionCommand)

	if err != nil {
		return err
	}

	*o = DefaultAssetsEntitiesInstructionCommand(varDefaultAssetsEntitiesInstructionCommand)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "instruction")
		delete(additionalProperties, "job_name")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDefaultAssetsEntitiesInstructionCommand struct {
	value *DefaultAssetsEntitiesInstructionCommand
	isSet bool
}

func (v NullableDefaultAssetsEntitiesInstructionCommand) Get() *DefaultAssetsEntitiesInstructionCommand {
	return v.value
}

func (v *NullableDefaultAssetsEntitiesInstructionCommand) Set(val *DefaultAssetsEntitiesInstructionCommand) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultAssetsEntitiesInstructionCommand) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultAssetsEntitiesInstructionCommand) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultAssetsEntitiesInstructionCommand(val *DefaultAssetsEntitiesInstructionCommand) *NullableDefaultAssetsEntitiesInstructionCommand {
	return &NullableDefaultAssetsEntitiesInstructionCommand{value: val, isSet: true}
}

func (v NullableDefaultAssetsEntitiesInstructionCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultAssetsEntitiesInstructionCommand) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
