/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
	"fmt"
)

// checks if the BillingServiceContactBillingInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingServiceContactBillingInfo{}

// BillingServiceContactBillingInfo struct for BillingServiceContactBillingInfo
type BillingServiceContactBillingInfo struct {
	Message              string `json:"message"`
	UserEmail            string `json:"user_email"`
	AdditionalProperties map[string]interface{}
}

type _BillingServiceContactBillingInfo BillingServiceContactBillingInfo

// NewBillingServiceContactBillingInfo instantiates a new BillingServiceContactBillingInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingServiceContactBillingInfo(message string, userEmail string) *BillingServiceContactBillingInfo {
	this := BillingServiceContactBillingInfo{}
	this.Message = message
	this.UserEmail = userEmail
	return &this
}

// NewBillingServiceContactBillingInfoWithDefaults instantiates a new BillingServiceContactBillingInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingServiceContactBillingInfoWithDefaults() *BillingServiceContactBillingInfo {
	this := BillingServiceContactBillingInfo{}
	return &this
}

// GetMessage returns the Message field value
func (o *BillingServiceContactBillingInfo) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BillingServiceContactBillingInfo) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BillingServiceContactBillingInfo) SetMessage(v string) {
	o.Message = v
}

// GetUserEmail returns the UserEmail field value
func (o *BillingServiceContactBillingInfo) GetUserEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserEmail
}

// GetUserEmailOk returns a tuple with the UserEmail field value
// and a boolean to check if the value has been set.
func (o *BillingServiceContactBillingInfo) GetUserEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserEmail, true
}

// SetUserEmail sets field value
func (o *BillingServiceContactBillingInfo) SetUserEmail(v string) {
	o.UserEmail = v
}

func (o BillingServiceContactBillingInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingServiceContactBillingInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["user_email"] = o.UserEmail

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BillingServiceContactBillingInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"user_email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingServiceContactBillingInfo := _BillingServiceContactBillingInfo{}

	err = json.Unmarshal(data, &varBillingServiceContactBillingInfo)

	if err != nil {
		return err
	}

	*o = BillingServiceContactBillingInfo(varBillingServiceContactBillingInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		delete(additionalProperties, "user_email")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBillingServiceContactBillingInfo struct {
	value *BillingServiceContactBillingInfo
	isSet bool
}

func (v NullableBillingServiceContactBillingInfo) Get() *BillingServiceContactBillingInfo {
	return v.value
}

func (v *NullableBillingServiceContactBillingInfo) Set(val *BillingServiceContactBillingInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingServiceContactBillingInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingServiceContactBillingInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingServiceContactBillingInfo(val *BillingServiceContactBillingInfo) *NullableBillingServiceContactBillingInfo {
	return &NullableBillingServiceContactBillingInfo{value: val, isSet: true}
}

func (v NullableBillingServiceContactBillingInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingServiceContactBillingInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
