/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the SentineloneGetVulnerableEndpointsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SentineloneGetVulnerableEndpointsResponse{}

// SentineloneGetVulnerableEndpointsResponse struct for SentineloneGetVulnerableEndpointsResponse
type SentineloneGetVulnerableEndpointsResponse struct {
	Data                 []ClientGetVulnerableEndpointsData `json:"data,omitempty"`
	Errors               []map[string]interface{}           `json:"errors,omitempty"`
	Pagination           *ClientPaginationResponse          `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SentineloneGetVulnerableEndpointsResponse SentineloneGetVulnerableEndpointsResponse

// NewSentineloneGetVulnerableEndpointsResponse instantiates a new SentineloneGetVulnerableEndpointsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSentineloneGetVulnerableEndpointsResponse() *SentineloneGetVulnerableEndpointsResponse {
	this := SentineloneGetVulnerableEndpointsResponse{}
	return &this
}

// NewSentineloneGetVulnerableEndpointsResponseWithDefaults instantiates a new SentineloneGetVulnerableEndpointsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSentineloneGetVulnerableEndpointsResponseWithDefaults() *SentineloneGetVulnerableEndpointsResponse {
	this := SentineloneGetVulnerableEndpointsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SentineloneGetVulnerableEndpointsResponse) GetData() []ClientGetVulnerableEndpointsData {
	if o == nil || IsNil(o.Data) {
		var ret []ClientGetVulnerableEndpointsData
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SentineloneGetVulnerableEndpointsResponse) GetDataOk() ([]ClientGetVulnerableEndpointsData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SentineloneGetVulnerableEndpointsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ClientGetVulnerableEndpointsData and assigns it to the Data field.
func (o *SentineloneGetVulnerableEndpointsResponse) SetData(v []ClientGetVulnerableEndpointsData) {
	o.Data = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *SentineloneGetVulnerableEndpointsResponse) GetErrors() []map[string]interface{} {
	if o == nil || IsNil(o.Errors) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SentineloneGetVulnerableEndpointsResponse) GetErrorsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *SentineloneGetVulnerableEndpointsResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []map[string]interface{} and assigns it to the Errors field.
func (o *SentineloneGetVulnerableEndpointsResponse) SetErrors(v []map[string]interface{}) {
	o.Errors = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *SentineloneGetVulnerableEndpointsResponse) GetPagination() ClientPaginationResponse {
	if o == nil || IsNil(o.Pagination) {
		var ret ClientPaginationResponse
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SentineloneGetVulnerableEndpointsResponse) GetPaginationOk() (*ClientPaginationResponse, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *SentineloneGetVulnerableEndpointsResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given ClientPaginationResponse and assigns it to the Pagination field.
func (o *SentineloneGetVulnerableEndpointsResponse) SetPagination(v ClientPaginationResponse) {
	o.Pagination = &v
}

func (o SentineloneGetVulnerableEndpointsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SentineloneGetVulnerableEndpointsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SentineloneGetVulnerableEndpointsResponse) UnmarshalJSON(data []byte) (err error) {
	varSentineloneGetVulnerableEndpointsResponse := _SentineloneGetVulnerableEndpointsResponse{}

	err = json.Unmarshal(data, &varSentineloneGetVulnerableEndpointsResponse)

	if err != nil {
		return err
	}

	*o = SentineloneGetVulnerableEndpointsResponse(varSentineloneGetVulnerableEndpointsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "errors")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSentineloneGetVulnerableEndpointsResponse struct {
	value *SentineloneGetVulnerableEndpointsResponse
	isSet bool
}

func (v NullableSentineloneGetVulnerableEndpointsResponse) Get() *SentineloneGetVulnerableEndpointsResponse {
	return v.value
}

func (v *NullableSentineloneGetVulnerableEndpointsResponse) Set(val *SentineloneGetVulnerableEndpointsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSentineloneGetVulnerableEndpointsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSentineloneGetVulnerableEndpointsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSentineloneGetVulnerableEndpointsResponse(val *SentineloneGetVulnerableEndpointsResponse) *NullableSentineloneGetVulnerableEndpointsResponse {
	return &NullableSentineloneGetVulnerableEndpointsResponse{value: val, isSet: true}
}

func (v NullableSentineloneGetVulnerableEndpointsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSentineloneGetVulnerableEndpointsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
