/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the AlertsServiceAlertNameStat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertsServiceAlertNameStat{}

// AlertsServiceAlertNameStat struct for AlertsServiceAlertNameStat
type AlertsServiceAlertNameStat struct {
	Name                 *string `json:"name,omitempty"`
	ResolvedCount        *int32  `json:"resolved_count,omitempty"`
	TotalCount           *int32  `json:"total_count,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AlertsServiceAlertNameStat AlertsServiceAlertNameStat

// NewAlertsServiceAlertNameStat instantiates a new AlertsServiceAlertNameStat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertsServiceAlertNameStat() *AlertsServiceAlertNameStat {
	this := AlertsServiceAlertNameStat{}
	return &this
}

// NewAlertsServiceAlertNameStatWithDefaults instantiates a new AlertsServiceAlertNameStat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertsServiceAlertNameStatWithDefaults() *AlertsServiceAlertNameStat {
	this := AlertsServiceAlertNameStat{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AlertsServiceAlertNameStat) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertsServiceAlertNameStat) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AlertsServiceAlertNameStat) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AlertsServiceAlertNameStat) SetName(v string) {
	o.Name = &v
}

// GetResolvedCount returns the ResolvedCount field value if set, zero value otherwise.
func (o *AlertsServiceAlertNameStat) GetResolvedCount() int32 {
	if o == nil || IsNil(o.ResolvedCount) {
		var ret int32
		return ret
	}
	return *o.ResolvedCount
}

// GetResolvedCountOk returns a tuple with the ResolvedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertsServiceAlertNameStat) GetResolvedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ResolvedCount) {
		return nil, false
	}
	return o.ResolvedCount, true
}

// HasResolvedCount returns a boolean if a field has been set.
func (o *AlertsServiceAlertNameStat) HasResolvedCount() bool {
	if o != nil && !IsNil(o.ResolvedCount) {
		return true
	}

	return false
}

// SetResolvedCount gets a reference to the given int32 and assigns it to the ResolvedCount field.
func (o *AlertsServiceAlertNameStat) SetResolvedCount(v int32) {
	o.ResolvedCount = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *AlertsServiceAlertNameStat) GetTotalCount() int32 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertsServiceAlertNameStat) GetTotalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *AlertsServiceAlertNameStat) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *AlertsServiceAlertNameStat) SetTotalCount(v int32) {
	o.TotalCount = &v
}

func (o AlertsServiceAlertNameStat) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertsServiceAlertNameStat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ResolvedCount) {
		toSerialize["resolved_count"] = o.ResolvedCount
	}
	if !IsNil(o.TotalCount) {
		toSerialize["total_count"] = o.TotalCount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AlertsServiceAlertNameStat) UnmarshalJSON(data []byte) (err error) {
	varAlertsServiceAlertNameStat := _AlertsServiceAlertNameStat{}

	err = json.Unmarshal(data, &varAlertsServiceAlertNameStat)

	if err != nil {
		return err
	}

	*o = AlertsServiceAlertNameStat(varAlertsServiceAlertNameStat)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "resolved_count")
		delete(additionalProperties, "total_count")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAlertsServiceAlertNameStat struct {
	value *AlertsServiceAlertNameStat
	isSet bool
}

func (v NullableAlertsServiceAlertNameStat) Get() *AlertsServiceAlertNameStat {
	return v.value
}

func (v *NullableAlertsServiceAlertNameStat) Set(val *AlertsServiceAlertNameStat) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertsServiceAlertNameStat) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertsServiceAlertNameStat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertsServiceAlertNameStat(val *AlertsServiceAlertNameStat) *NullableAlertsServiceAlertNameStat {
	return &NullableAlertsServiceAlertNameStat{value: val, isSet: true}
}

func (v NullableAlertsServiceAlertNameStat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertsServiceAlertNameStat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
