/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the DeviceUsersServiceStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceUsersServiceStats{}

// DeviceUsersServiceStats struct for DeviceUsersServiceStats
type DeviceUsersServiceStats struct {
	LastError            *string `json:"last_error,omitempty"`
	LastUsed             *string `json:"last_used,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeviceUsersServiceStats DeviceUsersServiceStats

// NewDeviceUsersServiceStats instantiates a new DeviceUsersServiceStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceUsersServiceStats() *DeviceUsersServiceStats {
	this := DeviceUsersServiceStats{}
	return &this
}

// NewDeviceUsersServiceStatsWithDefaults instantiates a new DeviceUsersServiceStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceUsersServiceStatsWithDefaults() *DeviceUsersServiceStats {
	this := DeviceUsersServiceStats{}
	return &this
}

// GetLastError returns the LastError field value if set, zero value otherwise.
func (o *DeviceUsersServiceStats) GetLastError() string {
	if o == nil || IsNil(o.LastError) {
		var ret string
		return ret
	}
	return *o.LastError
}

// GetLastErrorOk returns a tuple with the LastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsersServiceStats) GetLastErrorOk() (*string, bool) {
	if o == nil || IsNil(o.LastError) {
		return nil, false
	}
	return o.LastError, true
}

// HasLastError returns a boolean if a field has been set.
func (o *DeviceUsersServiceStats) HasLastError() bool {
	if o != nil && !IsNil(o.LastError) {
		return true
	}

	return false
}

// SetLastError gets a reference to the given string and assigns it to the LastError field.
func (o *DeviceUsersServiceStats) SetLastError(v string) {
	o.LastError = &v
}

// GetLastUsed returns the LastUsed field value if set, zero value otherwise.
func (o *DeviceUsersServiceStats) GetLastUsed() string {
	if o == nil || IsNil(o.LastUsed) {
		var ret string
		return ret
	}
	return *o.LastUsed
}

// GetLastUsedOk returns a tuple with the LastUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceUsersServiceStats) GetLastUsedOk() (*string, bool) {
	if o == nil || IsNil(o.LastUsed) {
		return nil, false
	}
	return o.LastUsed, true
}

// HasLastUsed returns a boolean if a field has been set.
func (o *DeviceUsersServiceStats) HasLastUsed() bool {
	if o != nil && !IsNil(o.LastUsed) {
		return true
	}

	return false
}

// SetLastUsed gets a reference to the given string and assigns it to the LastUsed field.
func (o *DeviceUsersServiceStats) SetLastUsed(v string) {
	o.LastUsed = &v
}

func (o DeviceUsersServiceStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceUsersServiceStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LastError) {
		toSerialize["last_error"] = o.LastError
	}
	if !IsNil(o.LastUsed) {
		toSerialize["last_used"] = o.LastUsed
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeviceUsersServiceStats) UnmarshalJSON(data []byte) (err error) {
	varDeviceUsersServiceStats := _DeviceUsersServiceStats{}

	err = json.Unmarshal(data, &varDeviceUsersServiceStats)

	if err != nil {
		return err
	}

	*o = DeviceUsersServiceStats(varDeviceUsersServiceStats)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "last_error")
		delete(additionalProperties, "last_used")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeviceUsersServiceStats struct {
	value *DeviceUsersServiceStats
	isSet bool
}

func (v NullableDeviceUsersServiceStats) Get() *DeviceUsersServiceStats {
	return v.value
}

func (v *NullableDeviceUsersServiceStats) Set(val *DeviceUsersServiceStats) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceUsersServiceStats) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceUsersServiceStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceUsersServiceStats(val *DeviceUsersServiceStats) *NullableDeviceUsersServiceStats {
	return &NullableDeviceUsersServiceStats{value: val, isSet: true}
}

func (v NullableDeviceUsersServiceStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceUsersServiceStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
