/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the SoftwareUpdatesServiceDdmInstalledSystemUpdates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SoftwareUpdatesServiceDdmInstalledSystemUpdates{}

// SoftwareUpdatesServiceDdmInstalledSystemUpdates struct for SoftwareUpdatesServiceDdmInstalledSystemUpdates
type SoftwareUpdatesServiceDdmInstalledSystemUpdates struct {
	BuildVersion         *string `json:"build_version,omitempty"`
	CreatedDate          *string `json:"created_date,omitempty"`
	DeviceUuid           *string `json:"device_uuid,omitempty"`
	OsVersion            *string `json:"os_version,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SoftwareUpdatesServiceDdmInstalledSystemUpdates SoftwareUpdatesServiceDdmInstalledSystemUpdates

// NewSoftwareUpdatesServiceDdmInstalledSystemUpdates instantiates a new SoftwareUpdatesServiceDdmInstalledSystemUpdates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoftwareUpdatesServiceDdmInstalledSystemUpdates() *SoftwareUpdatesServiceDdmInstalledSystemUpdates {
	this := SoftwareUpdatesServiceDdmInstalledSystemUpdates{}
	return &this
}

// NewSoftwareUpdatesServiceDdmInstalledSystemUpdatesWithDefaults instantiates a new SoftwareUpdatesServiceDdmInstalledSystemUpdates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoftwareUpdatesServiceDdmInstalledSystemUpdatesWithDefaults() *SoftwareUpdatesServiceDdmInstalledSystemUpdates {
	this := SoftwareUpdatesServiceDdmInstalledSystemUpdates{}
	return &this
}

// GetBuildVersion returns the BuildVersion field value if set, zero value otherwise.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) GetBuildVersion() string {
	if o == nil || IsNil(o.BuildVersion) {
		var ret string
		return ret
	}
	return *o.BuildVersion
}

// GetBuildVersionOk returns a tuple with the BuildVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) GetBuildVersionOk() (*string, bool) {
	if o == nil || IsNil(o.BuildVersion) {
		return nil, false
	}
	return o.BuildVersion, true
}

// HasBuildVersion returns a boolean if a field has been set.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) HasBuildVersion() bool {
	if o != nil && !IsNil(o.BuildVersion) {
		return true
	}

	return false
}

// SetBuildVersion gets a reference to the given string and assigns it to the BuildVersion field.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) SetBuildVersion(v string) {
	o.BuildVersion = &v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) GetCreatedDate() string {
	if o == nil || IsNil(o.CreatedDate) {
		var ret string
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) GetCreatedDateOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given string and assigns it to the CreatedDate field.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) SetCreatedDate(v string) {
	o.CreatedDate = &v
}

// GetDeviceUuid returns the DeviceUuid field value if set, zero value otherwise.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) GetDeviceUuid() string {
	if o == nil || IsNil(o.DeviceUuid) {
		var ret string
		return ret
	}
	return *o.DeviceUuid
}

// GetDeviceUuidOk returns a tuple with the DeviceUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) GetDeviceUuidOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceUuid) {
		return nil, false
	}
	return o.DeviceUuid, true
}

// HasDeviceUuid returns a boolean if a field has been set.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) HasDeviceUuid() bool {
	if o != nil && !IsNil(o.DeviceUuid) {
		return true
	}

	return false
}

// SetDeviceUuid gets a reference to the given string and assigns it to the DeviceUuid field.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) SetDeviceUuid(v string) {
	o.DeviceUuid = &v
}

// GetOsVersion returns the OsVersion field value if set, zero value otherwise.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) GetOsVersion() string {
	if o == nil || IsNil(o.OsVersion) {
		var ret string
		return ret
	}
	return *o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) GetOsVersionOk() (*string, bool) {
	if o == nil || IsNil(o.OsVersion) {
		return nil, false
	}
	return o.OsVersion, true
}

// HasOsVersion returns a boolean if a field has been set.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) HasOsVersion() bool {
	if o != nil && !IsNil(o.OsVersion) {
		return true
	}

	return false
}

// SetOsVersion gets a reference to the given string and assigns it to the OsVersion field.
func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) SetOsVersion(v string) {
	o.OsVersion = &v
}

func (o SoftwareUpdatesServiceDdmInstalledSystemUpdates) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SoftwareUpdatesServiceDdmInstalledSystemUpdates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BuildVersion) {
		toSerialize["build_version"] = o.BuildVersion
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["created_date"] = o.CreatedDate
	}
	if !IsNil(o.DeviceUuid) {
		toSerialize["device_uuid"] = o.DeviceUuid
	}
	if !IsNil(o.OsVersion) {
		toSerialize["os_version"] = o.OsVersion
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SoftwareUpdatesServiceDdmInstalledSystemUpdates) UnmarshalJSON(data []byte) (err error) {
	varSoftwareUpdatesServiceDdmInstalledSystemUpdates := _SoftwareUpdatesServiceDdmInstalledSystemUpdates{}

	err = json.Unmarshal(data, &varSoftwareUpdatesServiceDdmInstalledSystemUpdates)

	if err != nil {
		return err
	}

	*o = SoftwareUpdatesServiceDdmInstalledSystemUpdates(varSoftwareUpdatesServiceDdmInstalledSystemUpdates)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "build_version")
		delete(additionalProperties, "created_date")
		delete(additionalProperties, "device_uuid")
		delete(additionalProperties, "os_version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSoftwareUpdatesServiceDdmInstalledSystemUpdates struct {
	value *SoftwareUpdatesServiceDdmInstalledSystemUpdates
	isSet bool
}

func (v NullableSoftwareUpdatesServiceDdmInstalledSystemUpdates) Get() *SoftwareUpdatesServiceDdmInstalledSystemUpdates {
	return v.value
}

func (v *NullableSoftwareUpdatesServiceDdmInstalledSystemUpdates) Set(val *SoftwareUpdatesServiceDdmInstalledSystemUpdates) {
	v.value = val
	v.isSet = true
}

func (v NullableSoftwareUpdatesServiceDdmInstalledSystemUpdates) IsSet() bool {
	return v.isSet
}

func (v *NullableSoftwareUpdatesServiceDdmInstalledSystemUpdates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoftwareUpdatesServiceDdmInstalledSystemUpdates(val *SoftwareUpdatesServiceDdmInstalledSystemUpdates) *NullableSoftwareUpdatesServiceDdmInstalledSystemUpdates {
	return &NullableSoftwareUpdatesServiceDdmInstalledSystemUpdates{value: val, isSet: true}
}

func (v NullableSoftwareUpdatesServiceDdmInstalledSystemUpdates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoftwareUpdatesServiceDdmInstalledSystemUpdates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
