/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the HomescreenLayoutsEntitiesIconItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HomescreenLayoutsEntitiesIconItem{}

// HomescreenLayoutsEntitiesIconItem struct for HomescreenLayoutsEntitiesIconItem
type HomescreenLayoutsEntitiesIconItem struct {
	BundleId             *string                               `json:"bundle_id,omitempty"`
	DisplayName          *string                               `json:"display_name,omitempty"`
	Pages                [][]HomescreenLayoutsEntitiesIconItem `json:"pages,omitempty"`
	Type                 *string                               `json:"type,omitempty"`
	Url                  *string                               `json:"url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HomescreenLayoutsEntitiesIconItem HomescreenLayoutsEntitiesIconItem

// NewHomescreenLayoutsEntitiesIconItem instantiates a new HomescreenLayoutsEntitiesIconItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHomescreenLayoutsEntitiesIconItem() *HomescreenLayoutsEntitiesIconItem {
	this := HomescreenLayoutsEntitiesIconItem{}
	return &this
}

// NewHomescreenLayoutsEntitiesIconItemWithDefaults instantiates a new HomescreenLayoutsEntitiesIconItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHomescreenLayoutsEntitiesIconItemWithDefaults() *HomescreenLayoutsEntitiesIconItem {
	this := HomescreenLayoutsEntitiesIconItem{}
	return &this
}

// GetBundleId returns the BundleId field value if set, zero value otherwise.
func (o *HomescreenLayoutsEntitiesIconItem) GetBundleId() string {
	if o == nil || IsNil(o.BundleId) {
		var ret string
		return ret
	}
	return *o.BundleId
}

// GetBundleIdOk returns a tuple with the BundleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HomescreenLayoutsEntitiesIconItem) GetBundleIdOk() (*string, bool) {
	if o == nil || IsNil(o.BundleId) {
		return nil, false
	}
	return o.BundleId, true
}

// HasBundleId returns a boolean if a field has been set.
func (o *HomescreenLayoutsEntitiesIconItem) HasBundleId() bool {
	if o != nil && !IsNil(o.BundleId) {
		return true
	}

	return false
}

// SetBundleId gets a reference to the given string and assigns it to the BundleId field.
func (o *HomescreenLayoutsEntitiesIconItem) SetBundleId(v string) {
	o.BundleId = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *HomescreenLayoutsEntitiesIconItem) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HomescreenLayoutsEntitiesIconItem) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *HomescreenLayoutsEntitiesIconItem) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *HomescreenLayoutsEntitiesIconItem) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetPages returns the Pages field value if set, zero value otherwise.
func (o *HomescreenLayoutsEntitiesIconItem) GetPages() [][]HomescreenLayoutsEntitiesIconItem {
	if o == nil || IsNil(o.Pages) {
		var ret [][]HomescreenLayoutsEntitiesIconItem
		return ret
	}
	return o.Pages
}

// GetPagesOk returns a tuple with the Pages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HomescreenLayoutsEntitiesIconItem) GetPagesOk() ([][]HomescreenLayoutsEntitiesIconItem, bool) {
	if o == nil || IsNil(o.Pages) {
		return nil, false
	}
	return o.Pages, true
}

// HasPages returns a boolean if a field has been set.
func (o *HomescreenLayoutsEntitiesIconItem) HasPages() bool {
	if o != nil && !IsNil(o.Pages) {
		return true
	}

	return false
}

// SetPages gets a reference to the given [][]HomescreenLayoutsEntitiesIconItem and assigns it to the Pages field.
func (o *HomescreenLayoutsEntitiesIconItem) SetPages(v [][]HomescreenLayoutsEntitiesIconItem) {
	o.Pages = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *HomescreenLayoutsEntitiesIconItem) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HomescreenLayoutsEntitiesIconItem) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *HomescreenLayoutsEntitiesIconItem) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *HomescreenLayoutsEntitiesIconItem) SetType(v string) {
	o.Type = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *HomescreenLayoutsEntitiesIconItem) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HomescreenLayoutsEntitiesIconItem) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *HomescreenLayoutsEntitiesIconItem) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *HomescreenLayoutsEntitiesIconItem) SetUrl(v string) {
	o.Url = &v
}

func (o HomescreenLayoutsEntitiesIconItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HomescreenLayoutsEntitiesIconItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BundleId) {
		toSerialize["bundle_id"] = o.BundleId
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Pages) {
		toSerialize["pages"] = o.Pages
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HomescreenLayoutsEntitiesIconItem) UnmarshalJSON(data []byte) (err error) {
	varHomescreenLayoutsEntitiesIconItem := _HomescreenLayoutsEntitiesIconItem{}

	err = json.Unmarshal(data, &varHomescreenLayoutsEntitiesIconItem)

	if err != nil {
		return err
	}

	*o = HomescreenLayoutsEntitiesIconItem(varHomescreenLayoutsEntitiesIconItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bundle_id")
		delete(additionalProperties, "display_name")
		delete(additionalProperties, "pages")
		delete(additionalProperties, "type")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHomescreenLayoutsEntitiesIconItem struct {
	value *HomescreenLayoutsEntitiesIconItem
	isSet bool
}

func (v NullableHomescreenLayoutsEntitiesIconItem) Get() *HomescreenLayoutsEntitiesIconItem {
	return v.value
}

func (v *NullableHomescreenLayoutsEntitiesIconItem) Set(val *HomescreenLayoutsEntitiesIconItem) {
	v.value = val
	v.isSet = true
}

func (v NullableHomescreenLayoutsEntitiesIconItem) IsSet() bool {
	return v.isSet
}

func (v *NullableHomescreenLayoutsEntitiesIconItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHomescreenLayoutsEntitiesIconItem(val *HomescreenLayoutsEntitiesIconItem) *NullableHomescreenLayoutsEntitiesIconItem {
	return &NullableHomescreenLayoutsEntitiesIconItem{value: val, isSet: true}
}

func (v NullableHomescreenLayoutsEntitiesIconItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHomescreenLayoutsEntitiesIconItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
