/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the MdmServiceDevicesLostModeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MdmServiceDevicesLostModeRequest{}

// MdmServiceDevicesLostModeRequest struct for MdmServiceDevicesLostModeRequest
type MdmServiceDevicesLostModeRequest struct {
	AgentId              *string `json:"agent_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MdmServiceDevicesLostModeRequest MdmServiceDevicesLostModeRequest

// NewMdmServiceDevicesLostModeRequest instantiates a new MdmServiceDevicesLostModeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMdmServiceDevicesLostModeRequest() *MdmServiceDevicesLostModeRequest {
	this := MdmServiceDevicesLostModeRequest{}
	return &this
}

// NewMdmServiceDevicesLostModeRequestWithDefaults instantiates a new MdmServiceDevicesLostModeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMdmServiceDevicesLostModeRequestWithDefaults() *MdmServiceDevicesLostModeRequest {
	this := MdmServiceDevicesLostModeRequest{}
	return &this
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *MdmServiceDevicesLostModeRequest) GetAgentId() string {
	if o == nil || IsNil(o.AgentId) {
		var ret string
		return ret
	}
	return *o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmServiceDevicesLostModeRequest) GetAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *MdmServiceDevicesLostModeRequest) HasAgentId() bool {
	if o != nil && !IsNil(o.AgentId) {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given string and assigns it to the AgentId field.
func (o *MdmServiceDevicesLostModeRequest) SetAgentId(v string) {
	o.AgentId = &v
}

func (o MdmServiceDevicesLostModeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MdmServiceDevicesLostModeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentId) {
		toSerialize["agent_id"] = o.AgentId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MdmServiceDevicesLostModeRequest) UnmarshalJSON(data []byte) (err error) {
	varMdmServiceDevicesLostModeRequest := _MdmServiceDevicesLostModeRequest{}

	err = json.Unmarshal(data, &varMdmServiceDevicesLostModeRequest)

	if err != nil {
		return err
	}

	*o = MdmServiceDevicesLostModeRequest(varMdmServiceDevicesLostModeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "agent_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMdmServiceDevicesLostModeRequest struct {
	value *MdmServiceDevicesLostModeRequest
	isSet bool
}

func (v NullableMdmServiceDevicesLostModeRequest) Get() *MdmServiceDevicesLostModeRequest {
	return v.value
}

func (v *NullableMdmServiceDevicesLostModeRequest) Set(val *MdmServiceDevicesLostModeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMdmServiceDevicesLostModeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMdmServiceDevicesLostModeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMdmServiceDevicesLostModeRequest(val *MdmServiceDevicesLostModeRequest) *NullableMdmServiceDevicesLostModeRequest {
	return &NullableMdmServiceDevicesLostModeRequest{value: val, isSet: true}
}

func (v NullableMdmServiceDevicesLostModeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMdmServiceDevicesLostModeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
