/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pipedriveapi

import (
	"encoding/json"
)

// checks if the AlertEntitiesFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertEntitiesFilter{}

// AlertEntitiesFilter struct for AlertEntitiesFilter
type AlertEntitiesFilter struct {
	AgentIds             []string `json:"agent_ids,omitempty"`
	Category             *string  `json:"category,omitempty"`
	EndDate              *string  `json:"end_date,omitempty"`
	Ids                  []string `json:"ids,omitempty"`
	NameContains         *string  `json:"name_contains,omitempty"`
	RemediationStatus    *string  `json:"remediation_status,omitempty"`
	StartDate            *string  `json:"start_date,omitempty"`
	Statuses             []string `json:"statuses,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AlertEntitiesFilter AlertEntitiesFilter

// NewAlertEntitiesFilter instantiates a new AlertEntitiesFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertEntitiesFilter() *AlertEntitiesFilter {
	this := AlertEntitiesFilter{}
	return &this
}

// NewAlertEntitiesFilterWithDefaults instantiates a new AlertEntitiesFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertEntitiesFilterWithDefaults() *AlertEntitiesFilter {
	this := AlertEntitiesFilter{}
	return &this
}

// GetAgentIds returns the AgentIds field value if set, zero value otherwise.
func (o *AlertEntitiesFilter) GetAgentIds() []string {
	if o == nil || IsNil(o.AgentIds) {
		var ret []string
		return ret
	}
	return o.AgentIds
}

// GetAgentIdsOk returns a tuple with the AgentIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertEntitiesFilter) GetAgentIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AgentIds) {
		return nil, false
	}
	return o.AgentIds, true
}

// HasAgentIds returns a boolean if a field has been set.
func (o *AlertEntitiesFilter) HasAgentIds() bool {
	if o != nil && !IsNil(o.AgentIds) {
		return true
	}

	return false
}

// SetAgentIds gets a reference to the given []string and assigns it to the AgentIds field.
func (o *AlertEntitiesFilter) SetAgentIds(v []string) {
	o.AgentIds = v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *AlertEntitiesFilter) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertEntitiesFilter) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *AlertEntitiesFilter) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *AlertEntitiesFilter) SetCategory(v string) {
	o.Category = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *AlertEntitiesFilter) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertEntitiesFilter) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *AlertEntitiesFilter) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *AlertEntitiesFilter) SetEndDate(v string) {
	o.EndDate = &v
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *AlertEntitiesFilter) GetIds() []string {
	if o == nil || IsNil(o.Ids) {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertEntitiesFilter) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *AlertEntitiesFilter) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *AlertEntitiesFilter) SetIds(v []string) {
	o.Ids = v
}

// GetNameContains returns the NameContains field value if set, zero value otherwise.
func (o *AlertEntitiesFilter) GetNameContains() string {
	if o == nil || IsNil(o.NameContains) {
		var ret string
		return ret
	}
	return *o.NameContains
}

// GetNameContainsOk returns a tuple with the NameContains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertEntitiesFilter) GetNameContainsOk() (*string, bool) {
	if o == nil || IsNil(o.NameContains) {
		return nil, false
	}
	return o.NameContains, true
}

// HasNameContains returns a boolean if a field has been set.
func (o *AlertEntitiesFilter) HasNameContains() bool {
	if o != nil && !IsNil(o.NameContains) {
		return true
	}

	return false
}

// SetNameContains gets a reference to the given string and assigns it to the NameContains field.
func (o *AlertEntitiesFilter) SetNameContains(v string) {
	o.NameContains = &v
}

// GetRemediationStatus returns the RemediationStatus field value if set, zero value otherwise.
func (o *AlertEntitiesFilter) GetRemediationStatus() string {
	if o == nil || IsNil(o.RemediationStatus) {
		var ret string
		return ret
	}
	return *o.RemediationStatus
}

// GetRemediationStatusOk returns a tuple with the RemediationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertEntitiesFilter) GetRemediationStatusOk() (*string, bool) {
	if o == nil || IsNil(o.RemediationStatus) {
		return nil, false
	}
	return o.RemediationStatus, true
}

// HasRemediationStatus returns a boolean if a field has been set.
func (o *AlertEntitiesFilter) HasRemediationStatus() bool {
	if o != nil && !IsNil(o.RemediationStatus) {
		return true
	}

	return false
}

// SetRemediationStatus gets a reference to the given string and assigns it to the RemediationStatus field.
func (o *AlertEntitiesFilter) SetRemediationStatus(v string) {
	o.RemediationStatus = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *AlertEntitiesFilter) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertEntitiesFilter) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *AlertEntitiesFilter) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *AlertEntitiesFilter) SetStartDate(v string) {
	o.StartDate = &v
}

// GetStatuses returns the Statuses field value if set, zero value otherwise.
func (o *AlertEntitiesFilter) GetStatuses() []string {
	if o == nil || IsNil(o.Statuses) {
		var ret []string
		return ret
	}
	return o.Statuses
}

// GetStatusesOk returns a tuple with the Statuses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertEntitiesFilter) GetStatusesOk() ([]string, bool) {
	if o == nil || IsNil(o.Statuses) {
		return nil, false
	}
	return o.Statuses, true
}

// HasStatuses returns a boolean if a field has been set.
func (o *AlertEntitiesFilter) HasStatuses() bool {
	if o != nil && !IsNil(o.Statuses) {
		return true
	}

	return false
}

// SetStatuses gets a reference to the given []string and assigns it to the Statuses field.
func (o *AlertEntitiesFilter) SetStatuses(v []string) {
	o.Statuses = v
}

func (o AlertEntitiesFilter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertEntitiesFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentIds) {
		toSerialize["agent_ids"] = o.AgentIds
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.Ids) {
		toSerialize["ids"] = o.Ids
	}
	if !IsNil(o.NameContains) {
		toSerialize["name_contains"] = o.NameContains
	}
	if !IsNil(o.RemediationStatus) {
		toSerialize["remediation_status"] = o.RemediationStatus
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	if !IsNil(o.Statuses) {
		toSerialize["statuses"] = o.Statuses
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AlertEntitiesFilter) UnmarshalJSON(data []byte) (err error) {
	varAlertEntitiesFilter := _AlertEntitiesFilter{}

	err = json.Unmarshal(data, &varAlertEntitiesFilter)

	if err != nil {
		return err
	}

	*o = AlertEntitiesFilter(varAlertEntitiesFilter)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "agent_ids")
		delete(additionalProperties, "category")
		delete(additionalProperties, "end_date")
		delete(additionalProperties, "ids")
		delete(additionalProperties, "name_contains")
		delete(additionalProperties, "remediation_status")
		delete(additionalProperties, "start_date")
		delete(additionalProperties, "statuses")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAlertEntitiesFilter struct {
	value *AlertEntitiesFilter
	isSet bool
}

func (v NullableAlertEntitiesFilter) Get() *AlertEntitiesFilter {
	return v.value
}

func (v *NullableAlertEntitiesFilter) Set(val *AlertEntitiesFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertEntitiesFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertEntitiesFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertEntitiesFilter(val *AlertEntitiesFilter) *NullableAlertEntitiesFilter {
	return &NullableAlertEntitiesFilter{value: val, isSet: true}
}

func (v NullableAlertEntitiesFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertEntitiesFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
