/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the CorrelationEngineTypedCustomFilterRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorrelationEngineTypedCustomFilterRule{}

// CorrelationEngineTypedCustomFilterRule struct for CorrelationEngineTypedCustomFilterRule
type CorrelationEngineTypedCustomFilterRule struct {
	Created              *string           `json:"created,omitempty"`
	OrganizationId       *string           `json:"organization_id,omitempty"`
	Payload              *CustomFilterRule `json:"payload,omitempty"`
	RuleId               *string           `json:"rule_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CorrelationEngineTypedCustomFilterRule CorrelationEngineTypedCustomFilterRule

// NewCorrelationEngineTypedCustomFilterRule instantiates a new CorrelationEngineTypedCustomFilterRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorrelationEngineTypedCustomFilterRule() *CorrelationEngineTypedCustomFilterRule {
	this := CorrelationEngineTypedCustomFilterRule{}
	return &this
}

// NewCorrelationEngineTypedCustomFilterRuleWithDefaults instantiates a new CorrelationEngineTypedCustomFilterRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorrelationEngineTypedCustomFilterRuleWithDefaults() *CorrelationEngineTypedCustomFilterRule {
	this := CorrelationEngineTypedCustomFilterRule{}
	return &this
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *CorrelationEngineTypedCustomFilterRule) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorrelationEngineTypedCustomFilterRule) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *CorrelationEngineTypedCustomFilterRule) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *CorrelationEngineTypedCustomFilterRule) SetCreated(v string) {
	o.Created = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *CorrelationEngineTypedCustomFilterRule) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorrelationEngineTypedCustomFilterRule) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *CorrelationEngineTypedCustomFilterRule) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *CorrelationEngineTypedCustomFilterRule) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *CorrelationEngineTypedCustomFilterRule) GetPayload() CustomFilterRule {
	if o == nil || IsNil(o.Payload) {
		var ret CustomFilterRule
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorrelationEngineTypedCustomFilterRule) GetPayloadOk() (*CustomFilterRule, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *CorrelationEngineTypedCustomFilterRule) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given CustomFilterRule and assigns it to the Payload field.
func (o *CorrelationEngineTypedCustomFilterRule) SetPayload(v CustomFilterRule) {
	o.Payload = &v
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *CorrelationEngineTypedCustomFilterRule) GetRuleId() string {
	if o == nil || IsNil(o.RuleId) {
		var ret string
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorrelationEngineTypedCustomFilterRule) GetRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RuleId) {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *CorrelationEngineTypedCustomFilterRule) HasRuleId() bool {
	if o != nil && !IsNil(o.RuleId) {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given string and assigns it to the RuleId field.
func (o *CorrelationEngineTypedCustomFilterRule) SetRuleId(v string) {
	o.RuleId = &v
}

func (o CorrelationEngineTypedCustomFilterRule) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorrelationEngineTypedCustomFilterRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	if !IsNil(o.RuleId) {
		toSerialize["rule_id"] = o.RuleId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CorrelationEngineTypedCustomFilterRule) UnmarshalJSON(data []byte) (err error) {
	varCorrelationEngineTypedCustomFilterRule := _CorrelationEngineTypedCustomFilterRule{}

	err = json.Unmarshal(data, &varCorrelationEngineTypedCustomFilterRule)

	if err != nil {
		return err
	}

	*o = CorrelationEngineTypedCustomFilterRule(varCorrelationEngineTypedCustomFilterRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "created")
		delete(additionalProperties, "organization_id")
		delete(additionalProperties, "payload")
		delete(additionalProperties, "rule_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCorrelationEngineTypedCustomFilterRule struct {
	value *CorrelationEngineTypedCustomFilterRule
	isSet bool
}

func (v NullableCorrelationEngineTypedCustomFilterRule) Get() *CorrelationEngineTypedCustomFilterRule {
	return v.value
}

func (v *NullableCorrelationEngineTypedCustomFilterRule) Set(val *CorrelationEngineTypedCustomFilterRule) {
	v.value = val
	v.isSet = true
}

func (v NullableCorrelationEngineTypedCustomFilterRule) IsSet() bool {
	return v.isSet
}

func (v *NullableCorrelationEngineTypedCustomFilterRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorrelationEngineTypedCustomFilterRule(val *CorrelationEngineTypedCustomFilterRule) *NullableCorrelationEngineTypedCustomFilterRule {
	return &NullableCorrelationEngineTypedCustomFilterRule{value: val, isSet: true}
}

func (v NullableCorrelationEngineTypedCustomFilterRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorrelationEngineTypedCustomFilterRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
