/*
Addigy API Documentation

The [Addigy API](https://app.addigy.com/integrations) is designed to provide Addigy users with programmatic access to all data in their Addigy environment. Via the Addigy API users have read and write access to nearly all the data in their environment allowing them to automate activities in Addigy and integrate into 3rd party systems.<br> API keys can be created within your Addigy organization by visiting [Account -> Integrations](https://app.addigy.com/integrations).<br> **What does it mean if an API v2 endpoint is marked as \"Beta\"?** In rare cases, the required request and response data for an endpoint may change. Should a change be needed, Addigy will communicate the changes providing time for users to transition and test.<br> **Child Organizations** <br>Endpoints that have /oa/ in their path enable you to request data for an organization and its descendant organizations. To use this capability, there are two query parameters: <ul><li><b>multitenancy</b> (optional, boolean): When set to true, the request will include data for all descendant organizations (child, grandchild, etc.), allowing you to query across multiple organizations. If set to false or omitted, the request will return data only for your own organization.</li> <br><li><b>child-organizations</b> (optional, string): A comma-separated list of organization IDs to filter results for specific descendant organizations. If omitted, all child organizations will be included in the query by default if the multitenancy query param is set to true.</li></ul> <p>If you have questions or suggestions for the Addigy API Contact <a href=\"mailto:support@addigy.com\">Addigy Support</a></p>

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package addigyapi

import (
	"encoding/json"
)

// checks if the MaintenanceEntitiesMaintenancePost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MaintenanceEntitiesMaintenancePost{}

// MaintenanceEntitiesMaintenancePost struct for MaintenanceEntitiesMaintenancePost
type MaintenanceEntitiesMaintenancePost struct {
	Day                     *string                                 `json:"day,omitempty"`
	Description             *string                                 `json:"description,omitempty"`
	Enabled                 *bool                                   `json:"enabled,omitempty"`
	ExpectedRemediationTime *int32                                  `json:"expected_remediation_time,omitempty"`
	Frequency               *string                                 `json:"frequency,omitempty"`
	IsInBlueprint           *bool                                   `json:"is_in_blueprint,omitempty"`
	LocalTime               *bool                                   `json:"local_time,omitempty"`
	MaxTryCount             *int32                                  `json:"max_try_count,omitempty"`
	Name                    *string                                 `json:"name,omitempty"`
	PromptUser              *bool                                   `json:"prompt_user,omitempty"`
	ScheduledTime           *string                                 `json:"scheduled_time,omitempty"`
	Scripts                 []MaintenanceEntitiesInstructionCommand `json:"scripts,omitempty"`
	TimeoutSeconds          *int32                                  `json:"timeout_seconds,omitempty"`
	Version                 *int32                                  `json:"version,omitempty"`
	AdditionalProperties    map[string]interface{}
}

type _MaintenanceEntitiesMaintenancePost MaintenanceEntitiesMaintenancePost

// NewMaintenanceEntitiesMaintenancePost instantiates a new MaintenanceEntitiesMaintenancePost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaintenanceEntitiesMaintenancePost() *MaintenanceEntitiesMaintenancePost {
	this := MaintenanceEntitiesMaintenancePost{}
	return &this
}

// NewMaintenanceEntitiesMaintenancePostWithDefaults instantiates a new MaintenanceEntitiesMaintenancePost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaintenanceEntitiesMaintenancePostWithDefaults() *MaintenanceEntitiesMaintenancePost {
	this := MaintenanceEntitiesMaintenancePost{}
	return &this
}

// GetDay returns the Day field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetDay() string {
	if o == nil || IsNil(o.Day) {
		var ret string
		return ret
	}
	return *o.Day
}

// GetDayOk returns a tuple with the Day field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetDayOk() (*string, bool) {
	if o == nil || IsNil(o.Day) {
		return nil, false
	}
	return o.Day, true
}

// HasDay returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasDay() bool {
	if o != nil && !IsNil(o.Day) {
		return true
	}

	return false
}

// SetDay gets a reference to the given string and assigns it to the Day field.
func (o *MaintenanceEntitiesMaintenancePost) SetDay(v string) {
	o.Day = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *MaintenanceEntitiesMaintenancePost) SetDescription(v string) {
	o.Description = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *MaintenanceEntitiesMaintenancePost) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetExpectedRemediationTime returns the ExpectedRemediationTime field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetExpectedRemediationTime() int32 {
	if o == nil || IsNil(o.ExpectedRemediationTime) {
		var ret int32
		return ret
	}
	return *o.ExpectedRemediationTime
}

// GetExpectedRemediationTimeOk returns a tuple with the ExpectedRemediationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetExpectedRemediationTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpectedRemediationTime) {
		return nil, false
	}
	return o.ExpectedRemediationTime, true
}

// HasExpectedRemediationTime returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasExpectedRemediationTime() bool {
	if o != nil && !IsNil(o.ExpectedRemediationTime) {
		return true
	}

	return false
}

// SetExpectedRemediationTime gets a reference to the given int32 and assigns it to the ExpectedRemediationTime field.
func (o *MaintenanceEntitiesMaintenancePost) SetExpectedRemediationTime(v int32) {
	o.ExpectedRemediationTime = &v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetFrequency() string {
	if o == nil || IsNil(o.Frequency) {
		var ret string
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetFrequencyOk() (*string, bool) {
	if o == nil || IsNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasFrequency() bool {
	if o != nil && !IsNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given string and assigns it to the Frequency field.
func (o *MaintenanceEntitiesMaintenancePost) SetFrequency(v string) {
	o.Frequency = &v
}

// GetIsInBlueprint returns the IsInBlueprint field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetIsInBlueprint() bool {
	if o == nil || IsNil(o.IsInBlueprint) {
		var ret bool
		return ret
	}
	return *o.IsInBlueprint
}

// GetIsInBlueprintOk returns a tuple with the IsInBlueprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetIsInBlueprintOk() (*bool, bool) {
	if o == nil || IsNil(o.IsInBlueprint) {
		return nil, false
	}
	return o.IsInBlueprint, true
}

// HasIsInBlueprint returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasIsInBlueprint() bool {
	if o != nil && !IsNil(o.IsInBlueprint) {
		return true
	}

	return false
}

// SetIsInBlueprint gets a reference to the given bool and assigns it to the IsInBlueprint field.
func (o *MaintenanceEntitiesMaintenancePost) SetIsInBlueprint(v bool) {
	o.IsInBlueprint = &v
}

// GetLocalTime returns the LocalTime field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetLocalTime() bool {
	if o == nil || IsNil(o.LocalTime) {
		var ret bool
		return ret
	}
	return *o.LocalTime
}

// GetLocalTimeOk returns a tuple with the LocalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetLocalTimeOk() (*bool, bool) {
	if o == nil || IsNil(o.LocalTime) {
		return nil, false
	}
	return o.LocalTime, true
}

// HasLocalTime returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasLocalTime() bool {
	if o != nil && !IsNil(o.LocalTime) {
		return true
	}

	return false
}

// SetLocalTime gets a reference to the given bool and assigns it to the LocalTime field.
func (o *MaintenanceEntitiesMaintenancePost) SetLocalTime(v bool) {
	o.LocalTime = &v
}

// GetMaxTryCount returns the MaxTryCount field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetMaxTryCount() int32 {
	if o == nil || IsNil(o.MaxTryCount) {
		var ret int32
		return ret
	}
	return *o.MaxTryCount
}

// GetMaxTryCountOk returns a tuple with the MaxTryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetMaxTryCountOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTryCount) {
		return nil, false
	}
	return o.MaxTryCount, true
}

// HasMaxTryCount returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasMaxTryCount() bool {
	if o != nil && !IsNil(o.MaxTryCount) {
		return true
	}

	return false
}

// SetMaxTryCount gets a reference to the given int32 and assigns it to the MaxTryCount field.
func (o *MaintenanceEntitiesMaintenancePost) SetMaxTryCount(v int32) {
	o.MaxTryCount = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MaintenanceEntitiesMaintenancePost) SetName(v string) {
	o.Name = &v
}

// GetPromptUser returns the PromptUser field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetPromptUser() bool {
	if o == nil || IsNil(o.PromptUser) {
		var ret bool
		return ret
	}
	return *o.PromptUser
}

// GetPromptUserOk returns a tuple with the PromptUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetPromptUserOk() (*bool, bool) {
	if o == nil || IsNil(o.PromptUser) {
		return nil, false
	}
	return o.PromptUser, true
}

// HasPromptUser returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasPromptUser() bool {
	if o != nil && !IsNil(o.PromptUser) {
		return true
	}

	return false
}

// SetPromptUser gets a reference to the given bool and assigns it to the PromptUser field.
func (o *MaintenanceEntitiesMaintenancePost) SetPromptUser(v bool) {
	o.PromptUser = &v
}

// GetScheduledTime returns the ScheduledTime field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetScheduledTime() string {
	if o == nil || IsNil(o.ScheduledTime) {
		var ret string
		return ret
	}
	return *o.ScheduledTime
}

// GetScheduledTimeOk returns a tuple with the ScheduledTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetScheduledTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ScheduledTime) {
		return nil, false
	}
	return o.ScheduledTime, true
}

// HasScheduledTime returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasScheduledTime() bool {
	if o != nil && !IsNil(o.ScheduledTime) {
		return true
	}

	return false
}

// SetScheduledTime gets a reference to the given string and assigns it to the ScheduledTime field.
func (o *MaintenanceEntitiesMaintenancePost) SetScheduledTime(v string) {
	o.ScheduledTime = &v
}

// GetScripts returns the Scripts field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetScripts() []MaintenanceEntitiesInstructionCommand {
	if o == nil || IsNil(o.Scripts) {
		var ret []MaintenanceEntitiesInstructionCommand
		return ret
	}
	return o.Scripts
}

// GetScriptsOk returns a tuple with the Scripts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetScriptsOk() ([]MaintenanceEntitiesInstructionCommand, bool) {
	if o == nil || IsNil(o.Scripts) {
		return nil, false
	}
	return o.Scripts, true
}

// HasScripts returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasScripts() bool {
	if o != nil && !IsNil(o.Scripts) {
		return true
	}

	return false
}

// SetScripts gets a reference to the given []MaintenanceEntitiesInstructionCommand and assigns it to the Scripts field.
func (o *MaintenanceEntitiesMaintenancePost) SetScripts(v []MaintenanceEntitiesInstructionCommand) {
	o.Scripts = v
}

// GetTimeoutSeconds returns the TimeoutSeconds field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetTimeoutSeconds() int32 {
	if o == nil || IsNil(o.TimeoutSeconds) {
		var ret int32
		return ret
	}
	return *o.TimeoutSeconds
}

// GetTimeoutSecondsOk returns a tuple with the TimeoutSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetTimeoutSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeoutSeconds) {
		return nil, false
	}
	return o.TimeoutSeconds, true
}

// HasTimeoutSeconds returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasTimeoutSeconds() bool {
	if o != nil && !IsNil(o.TimeoutSeconds) {
		return true
	}

	return false
}

// SetTimeoutSeconds gets a reference to the given int32 and assigns it to the TimeoutSeconds field.
func (o *MaintenanceEntitiesMaintenancePost) SetTimeoutSeconds(v int32) {
	o.TimeoutSeconds = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *MaintenanceEntitiesMaintenancePost) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceEntitiesMaintenancePost) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *MaintenanceEntitiesMaintenancePost) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *MaintenanceEntitiesMaintenancePost) SetVersion(v int32) {
	o.Version = &v
}

func (o MaintenanceEntitiesMaintenancePost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MaintenanceEntitiesMaintenancePost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Day) {
		toSerialize["day"] = o.Day
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.ExpectedRemediationTime) {
		toSerialize["expected_remediation_time"] = o.ExpectedRemediationTime
	}
	if !IsNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if !IsNil(o.IsInBlueprint) {
		toSerialize["is_in_blueprint"] = o.IsInBlueprint
	}
	if !IsNil(o.LocalTime) {
		toSerialize["local_time"] = o.LocalTime
	}
	if !IsNil(o.MaxTryCount) {
		toSerialize["max_try_count"] = o.MaxTryCount
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PromptUser) {
		toSerialize["prompt_user"] = o.PromptUser
	}
	if !IsNil(o.ScheduledTime) {
		toSerialize["scheduled_time"] = o.ScheduledTime
	}
	if !IsNil(o.Scripts) {
		toSerialize["scripts"] = o.Scripts
	}
	if !IsNil(o.TimeoutSeconds) {
		toSerialize["timeout_seconds"] = o.TimeoutSeconds
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MaintenanceEntitiesMaintenancePost) UnmarshalJSON(data []byte) (err error) {
	varMaintenanceEntitiesMaintenancePost := _MaintenanceEntitiesMaintenancePost{}

	err = json.Unmarshal(data, &varMaintenanceEntitiesMaintenancePost)

	if err != nil {
		return err
	}

	*o = MaintenanceEntitiesMaintenancePost(varMaintenanceEntitiesMaintenancePost)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "day")
		delete(additionalProperties, "description")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "expected_remediation_time")
		delete(additionalProperties, "frequency")
		delete(additionalProperties, "is_in_blueprint")
		delete(additionalProperties, "local_time")
		delete(additionalProperties, "max_try_count")
		delete(additionalProperties, "name")
		delete(additionalProperties, "prompt_user")
		delete(additionalProperties, "scheduled_time")
		delete(additionalProperties, "scripts")
		delete(additionalProperties, "timeout_seconds")
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMaintenanceEntitiesMaintenancePost struct {
	value *MaintenanceEntitiesMaintenancePost
	isSet bool
}

func (v NullableMaintenanceEntitiesMaintenancePost) Get() *MaintenanceEntitiesMaintenancePost {
	return v.value
}

func (v *NullableMaintenanceEntitiesMaintenancePost) Set(val *MaintenanceEntitiesMaintenancePost) {
	v.value = val
	v.isSet = true
}

func (v NullableMaintenanceEntitiesMaintenancePost) IsSet() bool {
	return v.isSet
}

func (v *NullableMaintenanceEntitiesMaintenancePost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaintenanceEntitiesMaintenancePost(val *MaintenanceEntitiesMaintenancePost) *NullableMaintenanceEntitiesMaintenancePost {
	return &NullableMaintenanceEntitiesMaintenancePost{value: val, isSet: true}
}

func (v NullableMaintenanceEntitiesMaintenancePost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaintenanceEntitiesMaintenancePost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
